### ISSUE TITLE
[Feature Request] 提供关闭条目类型检查的设置入口

### ISSUE THREAD

**Issue by nkh0472** [northword/zotero-format-metadata#102]
### Describe the feature

我在保存文献时，除了保存自动导入的PDF文件，还会用网页右键的zotero官方浏览器插件手动保存一份文献的snapshot，之后再手动把snapshot合并到原条目中。这样做的目的是，HTML下，文章的断句未经破坏，相比起PDF更加适合复制和翻译的工作（尤其是用浏览器全文翻译）。
每次保存网页时，Linter都会弹出提示“Linter for Zotero 监测到您导入了一个 WebPage 条目，其 URL 中包含了主要学术出版商的域名，导入可能存在异常，请确认！”，十分影响使用。
因此希望提供关闭条目类型检查的设置入口。

**Comment by northword** [comment]
Zotero 转换器在抓取条目时，应该会自动保存 snapshot 的，所以不需要手动保存一个 webpage 条目。

你常用的是哪个网站（转换器）呢？

**Comment by nkh0472** [comment]
> Zotero 转换器在抓取条目时，应该会自动保存 snapshot 的，所以不需要手动保存一个 webpage 条目。
> 
> 你常用的是哪个网站（转换器）呢？

使用的网站非常广泛，常见的比如RSC、IOP、ACS等等；大概看了一下，IEEE、ScienceDirect会默认抓取网页，但前面提到的都不会抓取。

**Comment by northword** [comment]
预计下个版本加入

---

ACS 也是支持的，可能最近不能了

![image](https://github.com/northword/zotero-format-metadata/assets/44738481/095cf7b2-6572-43f5-b763-92e482ae826f)

**Comment by northword** [comment]
https://github.com/northword/zotero-format-metadata/releases/tag/v1.6.16

**Comment by nkh0472** [comment]
昨天开始（不保证自动更新的及时性，不能保证是最近一个版本引起的……），这个提示再次出现，且设置内相关的开关不见了；
且如果后台的提示不关掉的话（确定或者关闭提示窗口），网页将不会保存在Zotero；
只有在几秒内及时关掉后台的提示窗口，网页才能保存下来。

该现象今天已经多次复现，影响到使用体验。

版本Zotero 7.0.0-beta.55+9151fb355 (64-bit)，Linter 1.11.0

**Comment by northword** [comment]
.label = 网页条目不应连接到学术出版社（应为期刊文章或其他类型）

确认一下这个是处于关闭的呢

**Comment by northword** [comment]
此外，经测试，这个弹窗即便不关闭也不会影响条目存入，只是阻碍linter对其字段进行处理。

![image](https://github.com/northword/zotero-format-metadata/assets/44738481/90365419-6508-48b6-a89b-ce6cc744c144)

**Comment by nkh0472** [comment]
https://github.com/northword/zotero-format-metadata/assets/67589323/fc889da3-d146-4288-9c2b-c044f366d98c

复现见视频，提示框仅影响右键选择保存Web Page with Snapshot的情况：

- 不关闭提示窗口时，浏览器插件不显示正在保存Snapshot的进度，稍后提示An error occurred...，并且新建的条目内也没有附件（网页文件）；
- 关闭提示窗口后，浏览器插件才显示正在保存Snapshot，稍后附件保存成功；

如果是默认的既保存pdf又保存网页的情况就不会影响保存网页。

**Comment by northword** [comment]
![image](https://github.com/northword/zotero-format-metadata/assets/44738481/c29c958d-5ec1-4a7a-833d-b8b1f3ef7cd9)

临时切换为进度窗提示。

关闭这个可以禁用这个功能。

**Comment by nkh0472** [comment]
非常感谢 :>
