### ISSUE TITLE
[Feature Request] 手动触发批量补全期刊名缩写

### ISSUE THREAD

**Issue by nkh0472** [northword/zotero-format-metadata#103]
### Describe the feature

能否增加功能手动补全没有期刊名缩写的期刊（可以提供本地数据库和在线补全两种入口，或者进依靠内置的本地库也足够）。
这个功能用于处理在安装Linter之前已经导入Zotero文库内的文献。

**Comment by northword** [comment]
![image](https://github.com/northword/zotero-format-metadata/assets/44738481/467c455b-5342-477c-b233-00beadae93aa)

**Comment by nkh0472** [comment]
啊……没意识到Linter是有右键菜单的，还以为只有全自动功能。
这样的话，建议在首页readme.md和features.md里放个右键菜单的截图及相关简短说明：）
