### ISSUE TITLE
[Bug] 元数据无法更新

### ISSUE THREAD

**Issue by Snowbird8** [northword/zotero-format-metadata#109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 11 22H2
- Zotero Version: 7.0.0-beta.54+6b996d4f9 (64-bit)
- Addon Version:1.6.18

### Describe the bug

![13536](https://github.com/northword/zotero-format-metadata/assets/77492741/538adc7f-e319-404a-88d3-60c6089582fd)
元数据无法更新

[Linter for Zotero] An error occurred and the detailed error log is shown below: 
 
Array [ TypeError, {…} ]
​
0: TypeError: undefined has no properties
​​
columnNumber: 7354349
​​
fileName: "jar:file:///C:/Users/Pt/AppData/Roaming/Zotero/Zotero/Profiles/51akqgrq.default/extensions/zotero-format-metadata@northword.cn.xpi!/chrome/content/scripts/formatmetadata.js"
​​
lineNumber: 206
​​
message: "undefined has no properties"
​​
stack: "Oi@jar:file:///C:/Users/Pt/AppData/Roaming/Zotero/Zotero/Profiles/51akqgrq.default/extensions/zotero-format-metadata@northword.cn.xpi!/chrome/content/scripts/formatmetadata.js:206:7354349\n"
​​
<prototype>: TypeError.prototype { stack: "", … }
​​​
constructor: function TypeError()
​​​​
length: 1
​​​​
name: "TypeError"
​​​​
prototype: TypeError.prototype { stack: "", … }
​​​​​
constructor: function TypeError()
​​​​​​
length: 1
​​​​​​
name: "TypeError"
​​​​​​
prototype: TypeError.prototype { stack: "", … }
​​​​​​​
constructor: function TypeError()
​​​​​​​​
length: 1
​​​​​​​​
name: "TypeError"
​​​​​​​​
prototype: TypeError.prototype { stack: "", … }
​​​​​​​​​
constructor: function TypeError()
​​​​​​​​​​
length: 1
​​​​​​​​​​
name: "TypeError"
​​​​​​​​​​
prototype: TypeError.prototype { stack: "", … }
​​​​​​​​​​
<prototype>: function Error()
​​​​​​​​​
message: ""
​​​​​​​​​
name: "TypeError"
​​​​​​​​​
stack: ""
​​​​​​​​​
<prototype>: Error.prototype { stack: "", … }
​​​​​​​​
<prototype>: function Error()
​​​​​​​
message: ""
​​​​​​​
name: "TypeError"
​​​​​​​
stack: ""
​​​​​​​
<prototype>: Error.prototype { stack: "", … }
​​​​​​
<prototype>: function Error()
​​​​​
message: ""
​​​​​
name: "TypeError"
​​​​​
stack: ""
​​​​​
<prototype>: Error.prototype { stack: "", … }
​​​​​​
constructor: function Error()
​​​​​​
message: ""
​​​​​​
name: "Error"
​​​​​​
stack: ""
​​​​​​
toString: function toString()
​​​​​​
<get stack()>: function stack()
​​​​​​
<set stack()>: function stack()
​​​​​​
<prototype>: Object { … }
​​​​
<prototype>: function Error()
​​​
message: ""
​​​
name: "TypeError"
​​​
stack: ""
​​​
<prototype>: Error.prototype { stack: "", … }
​​​​
constructor: function Error()
​​​​
message: ""
​​​​
name: "Error"
​​​​
stack: ""
​​​​
toString: function toString()
​​​​
<get stack()>: function stack()
​​​​
<set stack()>: function stack()
​​​​
<prototype>: Object { … }
​
1: Object { _ObjectType: "Item", _objectTypePlural: "items", _ObjectTypePlural: "Items", … }
​
length: 2
​
<prototype>: Array []
formatmetadata.js:205:14113

### Anything else?

no

**Comment by northword** [comment]
无法复现，请确认执行操作时网络正常，确认访问 crossref 或 doi.org 正常。

**Comment by Snowbird8** [comment]
https://github.com/northword/zotero-format-metadata/assets/77492741/f65274b5-44d7-4ed0-a704-e13e50fcdbe5

这两个网站可以正常访问。

**Comment by northword** [comment]
我推测与 zotero translator 有关，尝试更新 translator 试试

![image](https://github.com/northword/zotero-format-metadata/assets/44738481/a656d264-f1b1-46e2-93e2-fafc1b478640)


或在 运行 JavaScript 里运行一下以下代码看看返回结果：

```js
const identifier = {
    itemType: "journalArticle",
    DOI: "10.1007/s10562-008-9655-6",
};

const translate = new Zotero.Translate.Search();
translate.setIdentifier(identifier);
const translators = await translate.getTranslators();
translate.setTranslator(translators);
return translate;
```

正常的应该返回如下信息：

```js
{
    "_handlers": [
        "translators": []
    ]
    "_currentState": null
    "_translatorInfo": {
        "translatorID": "d9b57cd5-5a9c-4946-8616-3bdf8edfcbb5"
        "label": "mEDRA"
        "creator": "Aurimas Vinckevicius"
        "target": "^https?://www\\.medra\\.org/servlet/view\\?"
        "minVersion": "3.0"
        "maxVersion": ""
        "priority": 105
        "inRepository": true
        "translatorType": 12
        "browserSupport": "g"
        "lastUpdated": "2014-05-26 03:50:55"
    }
    "_translatorProvider": {
        "TRANSLATOR_ID_MARKDOWN_AND_RICH_TEXT": "a45eca67-1ee8-45e5-b4c6-23fb8a852873"
        "TRANSLATOR_ID_NOTE_MARKDOWN": "1412e9e2-51e1-42ec-aa35-e036a895534b"
        "TRANSLATOR_ID_NOTE_HTML": "897a81c2-9f60-4bec-ae6b-85a5030b8be5"
        "TRANSLATOR_ID_RDF": "5e3ad958-ac79-463d-812b-a86a9235c28f"
        "init": function () {...}
        "reinit": async function (options = {...}
        "load": function (json, path, code) {...}
        "loadFromFile": async function (path) {...}
        "get": function (id) {...}
        "getCodeForTranslator": function () {...}
        "getAllForType": async function (type) {...}
        "getAll": async function () {...}
        "getWebTranslatorsForLocation": function (URI, rootURI) {...}
        "getSearchURIs": function (URI) {...}
        "getImportTranslatorsForLocation": function (location, callback) {...}
        "getFileNameFromLabel": function (label, alternative) {...}
        "getTranslatorsDirectory": function () {...}
        "save": function () {...}
        "cacheInDB": function (fileName, metadataJSON, lastModifiedTime) {...}
        "makeTranslatorProvider": function (methods) {...}
    }
    "document": null
    "location": null
    "search": {
        "itemType": "journalArticle"
        "DOI": "10.1007/s10562-008-9655-6"
    }
    "_getAllTranslators": true
    "_potentialTranslators": []
    "_foundTranslators": [
        "0": {
            "proxy": null
            "translatorID": "b28d0d42-8549-4c6d-83fc-8382874a5cb9"
            "translatorType": 8
            "label": "DOI Content Negotiation"
            "creator": "Sebastian Karcher"
            "target": null
            "priority": 100
            "lastUpdated": "2023-09-22 10:50:00"
            "browserSupport": "g"
            "minVersion": "5.0"
            "maxVersion": null
            "inRepository": true
            "runMode": 1
            "cacheCode": undefined
            "path": "D:\\Northword\\Documents\\Zotero\\translators\\DOI Content Negotiation.js"
            "fileName": "DOI Content Negotiation.js"
            "metadata": {
                "translatorID": "b28d0d42-8549-4c6d-83fc-8382874a5cb9"
                "translatorType": 8
                "label": "DOI Content Negotiation"
                "creator": "Sebastian Karcher"
                "target": null
                "priority": 100
                "lastUpdated": "2023-09-22 10:50:00"
                "browserSupport": "g"
                "minVersion": "5.0"
                "maxVersion": null
                "inRepository": true
            }
            "init": function(info) {...}
            "serialize": function(properties) {...}
            "logError": function(message, type, line, lineNumber, colNumber) {...}
            "itemType": true
        }
        "1": {
            "proxy": null
            "translatorID": "d9b57cd5-5a9c-4946-8616-3bdf8edfcbb5"
            "translatorType": 12
            "label": "mEDRA"
            "creator": "Aurimas Vinckevicius"
            "target": "^https?://www\\.medra\\.org/servlet/view\\?"
            "priority": 105
            "lastUpdated": "2014-05-26 03:50:55"
            "browserSupport": "g"
            "minVersion": "3.0"
            "maxVersion": ""
            "inRepository": true
            "runMode": 1
            "cacheCode": 0
            "webRegexp": {
                "root": [object RegExp] {}
                "all": null
            }
            "path": "D:\\Northword\\Documents\\Zotero\\translators\\mEDRA.js"
            "fileName": "mEDRA.js"
            "metadata": {
                "translatorID": "d9b57cd5-5a9c-4946-8616-3bdf8edfcbb5"
                "translatorType": 12
                "label": "mEDRA"
                "creator": "Aurimas Vinckevicius"
                "target": "^https?://www\\.medra\\.org/servlet/view\\?"
                "priority": 105
                "lastUpdated": "2014-05-26 03:50:55"
                "browserSupport": "g"
                "minVersion": "3.0"
                "maxVersion": ""
                "inRepository": true
            }
            "init": function(info) {...}
            "serialize": function(properties) {...}
            "logError": function(message, type, line, lineNumber, colNumber) {...}
            "itemType": true
        }
    ]
    "_proxies": null
    "_waitingForRPC": false
    "_sandboxLocation": "http://www.example.com/"
    "_sandboxManager": {
        "sandbox": {
            "Zotero": {
                "Item": function (itemType) {...}
                "_itemDone": function () {...}
                "getOption": function () {...}
                "getHiddenPref": function () {...}
                "loadTranslator": function () {...}
                "wait": function () {...}
                "done": function () {...}
                "debug": function () {...}
                "Utilities": function () {...}
                "isBookmarklet": false
                "isConnector": false
                "isServer": false
                "parentTranslator": null
            }
            "XPathResult": {
                "ANY_TYPE": 0
                "NUMBER_TYPE": 1
                "STRING_TYPE": 2
                "BOOLEAN_TYPE": 3
                "UNORDERED_NODE_ITERATOR_TYPE": 4
                "ORDERED_NODE_ITERATOR_TYPE": 5
                "UNORDERED_NODE_SNAPSHOT_TYPE": 6
                "ORDERED_NODE_SNAPSHOT_TYPE": 7
                "ANY_UNORDERED_NODE_TYPE": 8
                "FIRST_ORDERED_NODE_TYPE": 9
            }
            "DOMParser": function () {...}
            "XMLSerializer": function () {...}
            "Z": {
                "Item": function (itemType) {...}
                "_itemDone": function () {...}
                "getOption": function () {...}
                "getHiddenPref": function () {...}
                "loadTranslator": function () {...}
                "wait": function () {...}
                "done": function () {...}
                "debug": function () {...}
                "Utilities": function () {...}
                "isBookmarklet": false
                "isConnector": false
                "isServer": false
                "parentTranslator": null
            }
            "ZU": function () {...}
            "attr": function() { [native code] }
            "text": function() { [native code] }
            "innerText": function() { [native code] }
            "request": function() { [native code] }
            "requestText": function() { [native code] }
            "requestJSON": function() { [native code] }
            "requestDocument": function() { [native code] }
            "detectSearch": function detectSearch(queries) {...}
            "doSearch": function doSearch(queries) {...}
            "exports": {}
            "ZOTERO_TRANSLATOR_INFO": {
                "translatorID": "d9b57cd5-5a9c-4946-8616-3bdf8edfcbb5"
                "label": "mEDRA"
                "creator": "Aurimas Vinckevicius"
                "target": "^https?://www\\.medra\\.org/servlet/view\\?"
                "minVersion": "3.0"
                "maxVersion": ""
                "priority": 105
                "inRepository": true
                "translatorType": 12
                "browserSupport": "g"
                "lastUpdated": "2014-05-26 03:50:55"
            }
        }
        "eval": function (code, functions) {...}
        "importObject": function (object, passAsFirstArgument, attachTo) {...}
    }
    "_sandboxZotero": {
        "Item": function (itemType) {...}
        "_itemDone": function () {...}
        "getOption": function () {...}
        "getHiddenPref": function () {...}
        "loadTranslator": function () {...}
        "wait": function () {...}
        "done": function () {...}
        "debug": function () {...}
        "Utilities": function () {...}
        "isBookmarklet": false
        "isConnector": false
        "isServer": false
        "parentTranslator": null
    }
    "_transferItem": undefined
    "_currentTranslator": {
        "translatorID": "d9b57cd5-5a9c-4946-8616-3bdf8edfcbb5"
        "translatorType": 12
        "label": "mEDRA"
        "creator": "Aurimas Vinckevicius"
        "target": "^https?://www\\.medra\\.org/servlet/view\\?"
        "priority": 105
        "lastUpdated": "2014-05-26 03:50:55"
        "browserSupport": "g"
        "minVersion": "3.0"
        "maxVersion": ""
        "inRepository": true
        "runMode": 1
        "cacheCode": 0
        "webRegexp": {
            "root": [object RegExp] {}
            "all": null
        }
        "path": "D:\\Northword\\Documents\\Zotero\\translators\\mEDRA.js"
        "fileName": "mEDRA.js"
        "metadata": {
            "translatorID": "d9b57cd5-5a9c-4946-8616-3bdf8edfcbb5"
            "translatorType": 12
            "label": "mEDRA"
            "creator": "Aurimas Vinckevicius"
            "target": "^https?://www\\.medra\\.org/servlet/view\\?"
            "priority": 105
            "lastUpdated": "2014-05-26 03:50:55"
            "browserSupport": "g"
            "minVersion": "3.0"
            "maxVersion": ""
            "inRepository": true
        }
        "init": function(info) {...}
        "serialize": function(properties) {...}
        "logError": function(message, type, line, lineNumber, colNumber) {...}
    }
    "_proxy": null
    "_runningAsyncProcesses": 0
    "_returnValue": true
    "_aborted": false
    "saveQueue": []
    "translator": [
        "0": {
            "proxy": null
            "translatorID": "b28d0d42-8549-4c6d-83fc-8382874a5cb9"
            "translatorType": 8
            "label": "DOI Content Negotiation"
            "creator": "Sebastian Karcher"
            "target": null
            "priority": 100
            "lastUpdated": "2023-09-22 10:50:00"
            "browserSupport": "g"
            "minVersion": "5.0"
            "maxVersion": null
            "inRepository": true
            "runMode": 1
            "cacheCode": undefined
            "path": "D:\\Northword\\Documents\\Zotero\\translators\\DOI Content Negotiation.js"
            "fileName": "DOI Content Negotiation.js"
            "metadata": {
                "translatorID": "b28d0d42-8549-4c6d-83fc-8382874a5cb9"
                "translatorType": 8
                "label": "DOI Content Negotiation"
                "creator": "Sebastian Karcher"
                "target": null
                "priority": 100
                "lastUpdated": "2023-09-22 10:50:00"
                "browserSupport": "g"
                "minVersion": "5.0"
                "maxVersion": null
                "inRepository": true
            }
            "init": function(info) {...}
            "serialize": function(properties) {...}
            "logError": function(message, type, line, lineNumber, colNumber) {...}
            "itemType": true
        }
        "1": {
            "proxy": null
            "translatorID": "d9b57cd5-5a9c-4946-8616-3bdf8edfcbb5"
            "translatorType": 12
            "label": "mEDRA"
            "creator": "Aurimas Vinckevicius"
            "target": "^https?://www\\.medra\\.org/servlet/view\\?"
            "priority": 105
            "lastUpdated": "2014-05-26 03:50:55"
            "browserSupport": "g"
            "minVersion": "3.0"
            "maxVersion": ""
            "inRepository": true
            "runMode": 1
            "cacheCode": 0
            "webRegexp": {
                "root": [object RegExp] {}
                "all": null
            }
            "path": "D:\\Northword\\Documents\\Zotero\\translators\\mEDRA.js"
            "fileName": "mEDRA.js"
            "metadata": {
                "translatorID": "d9b57cd5-5a9c-4946-8616-3bdf8edfcbb5"
                "translatorType": 12
                "label": "mEDRA"
                "creator": "Aurimas Vinckevicius"
                "target": "^https?://www\\.medra\\.org/servlet/view\\?"
                "priority": 105
                "lastUpdated": "2014-05-26 03:50:55"
                "browserSupport": "g"
                "minVersion": "3.0"
                "maxVersion": ""
                "inRepository": true
            }
            "init": function(info) {...}
            "serialize": function(properties) {...}
            "logError": function(message, type, line, lineNumber, colNumber) {...}
            "itemType": true
        }
    ]
    "type": "search"
    "_entryFunctionSuffix": "Search"
    "Sandbox": {
        "_itemDone": function(translate, item) {...}
        "getOption": function(translate, option) {...}
        "getHiddenPref": function(translate, pref) {...}
        "loadTranslator": function(translate, type) {...}
        "wait": function(translate) {...}
        "done": function(translate, returnValue) {...}
        "debug": function(translate, string, level) {...}
    }
    "ERROR_NO_RESULTS": "No items returned from any translator"
    "setCookieSandbox": function(cookieSandbox) {...}
    "setSearch": function(search) {...}
    "setIdentifier": function (identifier) {...}
    "getTranslators": function() {...}
    "complete": function(returnValue, error) {...}
    "_getParameters": function() {...}
    "_getSandboxLocation": function() {...}
    "_prepareTranslation": function () {...}
    "init": function() {...}
    "setLocation": function(location) {...}
    "setTranslator": function(translator) {...}
    "setHandler": function(type, handler) {...}
    "clearHandlers": function(type) {...}
    "removeHandler": function(type, handler) {...}
    "setTranslatorProvider": function (translatorProvider) {...}
    "incrementAsyncProcesses": function(f) {...}
    "decrementAsyncProcesses": function(f, by) {...}
    "_runHandler": function(type) {...}
    "_getTranslatorsGetPotentialTranslators": async function () {...}
    "translate": function () {...}
    "_translateTranslatorLoaded": function () {...}
    "getProgress": function() {...}
    "resolveURL": function(url, dontUseProxy) {...}
    "_cleanTitle": function (title, itemType) {...}
    "_cleanTags": function(tags) {...}
    "_saveItems": function () {...}
    "_checkIfDone": function() {...}
    "_detect": async function() {...}
    "_detectTranslatorLoaded": async function () {...}
    "_detectTranslatorsCollected": function() {...}
    "_loadTranslator": function () {...}
    "_generateSandbox": function() {...}
    "_attr": function (selector, attr, index) {...}
    "_text": function (selector, index) {...}
    "_innerText": function (selector, index) {...}
    "_debug": function(string, level) {...}
    "_generateErrorString": function (error) {...}
    "_prepareDetection": function() {...}
}
```

如果报错了，那就是 Zotero translator 的问题，插件只是调用了这个功能。

**Comment by Snowbird8** [comment]
1、translator更新了，但还是报错，和之前的一模一样。
2、“运行 JavaScript 里运行一下以下代码看看返回结果”，这个不会。

**Comment by northword** [comment]
![image](https://github.com/northword/zotero-format-metadata/assets/44738481/d1c19846-5a34-4804-b6d1-52b638767d8b)

![image](https://github.com/northword/zotero-format-metadata/assets/44738481/7d8d645a-9238-4209-96b5-ffb03ef2e68b)

**Comment by Snowbird8** [comment]
得到了如下结果，我录屏了。请问是否能分析出是什么原因？

https://github.com/northword/zotero-format-metadata/assets/77492741/9bcba2b5-e8e4-43ac-a875-0111e818394f

{
    "_handlers": [
        "translators": []
    ]
    "_currentState": null
    "_translatorInfo": {
        "translatorID": "9a0ecbda-c0e9-4a19-84a9-fc8e7c845afa"
        "translatorType": 12
        "label": "Lulu"
        "creator": "Aurimas Vinckevicius"
        "target": "^https?://www\\.lulu\\.com/shop/"
        "minVersion": "3.0"
        "maxVersion": null
        "priority": 101
        "inRepository": true
        "browserSupport": "gcsibv"
        "lastUpdated": "2023-04-27 09:30:00"
    }
    "_translatorProvider": {
        "TRANSLATOR_ID_MARKDOWN_AND_RICH_TEXT": "a45eca67-1ee8-45e5-b4c6-23fb8a852873"
        "TRANSLATOR_ID_NOTE_MARKDOWN": "1412e9e2-51e1-42ec-aa35-e036a895534b"
        "TRANSLATOR_ID_NOTE_HTML": "897a81c2-9f60-4bec-ae6b-85a5030b8be5"
        "TRANSLATOR_ID_RDF": "5e3ad958-ac79-463d-812b-a86a9235c28f"
        "_translatorsHash": "b9871262c7403dcfbfabb5eb9627e39f"
        "init": function () {...}
        "reinit": async function (options = {...}
        "load": function (json, path, code) {...}
        "loadFromFile": async function (path) {...}
        "getTranslatorsHash": async function () {...}
        "get": function (id) {...}
        "getCodeForTranslator": function () {...}
        "getAllForType": async function (type) {...}
        "getAll": async function () {...}
        "getWebTranslatorsForLocation": function (URI, rootURI) {...}
        "getSearchURIs": function (URI) {...}
        "getImportTranslatorsForLocation": function (location, callback) {...}
        "getFileNameFromLabel": function (label, alternative) {...}
        "getTranslatorsDirectory": function () {...}
        "save": function () {...}
        "cacheInDB": function (fileName, metadataJSON, lastModifiedTime) {...}
        "makeTranslatorProvider": function (methods) {...}
    }
    "document": null
    "location": null
    "search": {
        "itemType": "journalArticle"
        "DOI": "10.1007/s10562-008-9655-6"
    }
    "_getAllTranslators": true
    "_potentialTranslators": []
    "_foundTranslators": [
        "0": {
            "proxy": null
            "translatorID": "b28d0d42-8549-4c6d-83fc-8382874a5cb9"
            "translatorType": 8
            "label": "DOI Content Negotiation"
            "creator": "Sebastian Karcher"
            "target": null
            "priority": 100
            "lastUpdated": "2023-09-22 10:50:00"
            "browserSupport": "g"
            "minVersion": "5.0"
            "maxVersion": null
            "inRepository": true
            "runMode": 1
            "cacheCode": undefined
            "path": "D:\\Zotero\\translators\\DOI Content Negotiation.js"
            "fileName": "DOI Content Negotiation.js"
            "metadata": {
                "translatorID": "b28d0d42-8549-4c6d-83fc-8382874a5cb9"
                "translatorType": 8
                "label": "DOI Content Negotiation"
                "creator": "Sebastian Karcher"
                "target": null
                "priority": 100
                "lastUpdated": "2023-09-22 10:50:00"
                "browserSupport": "g"
                "minVersion": "5.0"
                "maxVersion": null
                "inRepository": true
            }
            "init": function(info) {...}
            "serialize": function(properties) {...}
            "logError": function(message, type, line, lineNumber, colNumber) {...}
            "itemType": true
        }
    ]
    "_proxies": null
    "_waitingForRPC": false
    "_sandboxLocation": "http://www.example.com/"
    "_sandboxManager": {
        "sandbox": {
            "Zotero": {
                "Item": function (itemType) {...}
                "_itemDone": function () {...}
                "getOption": function () {...}
                "getHiddenPref": function () {...}
                "loadTranslator": function () {...}
                "wait": function () {...}
                "done": function () {...}
                "debug": function () {...}
                "Utilities": function () {...}
                "isBookmarklet": false
                "isConnector": false
                "isServer": false
                "parentTranslator": null
            }
            "XPathResult": {
                "ANY_TYPE": 0
                "NUMBER_TYPE": 1
                "STRING_TYPE": 2
                "BOOLEAN_TYPE": 3
                "UNORDERED_NODE_ITERATOR_TYPE": 4
                "ORDERED_NODE_ITERATOR_TYPE": 5
                "UNORDERED_NODE_SNAPSHOT_TYPE": 6
                "ORDERED_NODE_SNAPSHOT_TYPE": 7
                "ANY_UNORDERED_NODE_TYPE": 8
                "FIRST_ORDERED_NODE_TYPE": 9
            }
            "DOMParser": function () {...}
            "XMLSerializer": function () {...}
            "Z": {
                "Item": function (itemType) {...}
                "_itemDone": function () {...}
                "getOption": function () {...}
                "getHiddenPref": function () {...}
                "loadTranslator": function () {...}
                "wait": function () {...}
                "done": function () {...}
                "debug": function () {...}
                "Utilities": function () {...}
                "isBookmarklet": false
                "isConnector": false
                "isServer": false
                "parentTranslator": null
            }
            "ZU": function () {...}
            "attr": function() { [native code] }
            "text": function() { [native code] }
            "innerText": function() { [native code] }
            "request": function() { [native code] }
            "requestText": function() { [native code] }
            "requestJSON": function() { [native code] }
            "requestDocument": function() { [native code] }
            "detectSearch": function detectSearch(items) {...}
            "doSearch": function doSearch(items) {...}
            "exports": {}
            "ZOTERO_TRANSLATOR_INFO": {
                "translatorID": "9a0ecbda-c0e9-4a19-84a9-fc8e7c845afa"
                "translatorType": 12
                "label": "Lulu"
                "creator": "Aurimas Vinckevicius"
                "target": "^https?://www\\.lulu\\.com/shop/"
                "minVersion": "3.0"
                "maxVersion": null
                "priority": 101
                "inRepository": true
                "browserSupport": "gcsibv"
                "lastUpdated": "2023-04-27 09:30:00"
            }
        }
        "eval": function (code, functions) {...}
        "importObject": function (object, passAsFirstArgument, attachTo) {...}
    }
    "_sandboxZotero": {
        "Item": function (itemType) {...}
        "_itemDone": function () {...}
        "getOption": function () {...}
        "getHiddenPref": function () {...}
        "loadTranslator": function () {...}
        "wait": function () {...}
        "done": function () {...}
        "debug": function () {...}
        "Utilities": function () {...}
        "isBookmarklet": false
        "isConnector": false
        "isServer": false
        "parentTranslator": null
    }
    "_transferItem": undefined
    "_currentTranslator": {
        "translatorID": "d9b57cd5-5a9c-4946-8616-3bdf8edfcbb5"
        "translatorType": 12
        "label": "mEDRA"
        "creator": "Aurimas Vinckevicius"
        "target": "^https?://www\\.medra\\.org/servlet/view\\?"
        "priority": 105
        "lastUpdated": "2014-05-26 03:50:55"
        "browserSupport": "g"
        "minVersion": "3.0"
        "maxVersion": ""
        "inRepository": true
        "runMode": 1
        "cacheCode": 0
        "webRegexp": {
            "root": [object RegExp] {}
            "all": null
        }
        "path": "D:\\Zotero\\translators\\mEDRA.js"
        "fileName": "mEDRA.js"
        "metadata": {
            "translatorID": "d9b57cd5-5a9c-4946-8616-3bdf8edfcbb5"
            "translatorType": 12
            "label": "mEDRA"
            "creator": "Aurimas Vinckevicius"
            "target": "^https?://www\\.medra\\.org/servlet/view\\?"
            "priority": 105
            "lastUpdated": "2014-05-26 03:50:55"
            "browserSupport": "g"
            "minVersion": "3.0"
            "maxVersion": ""
            "inRepository": true
        }
        "init": function(info) {...}
        "serialize": function(properties) {...}
        "logError": function(message, type, line, lineNumber, colNumber) {...}
    }
    "_proxy": null
    "_runningAsyncProcesses": 0
    "_returnValue": false
    "_aborted": false
    "saveQueue": []
    "translator": [
        "0": {
            "proxy": null
            "translatorID": "b28d0d42-8549-4c6d-83fc-8382874a5cb9"
            "translatorType": 8
            "label": "DOI Content Negotiation"
            "creator": "Sebastian Karcher"
            "target": null
            "priority": 100
            "lastUpdated": "2023-09-22 10:50:00"
            "browserSupport": "g"
            "minVersion": "5.0"
            "maxVersion": null
            "inRepository": true
            "runMode": 1
            "cacheCode": undefined
            "path": "D:\\Zotero\\translators\\DOI Content Negotiation.js"
            "fileName": "DOI Content Negotiation.js"
            "metadata": {
                "translatorID": "b28d0d42-8549-4c6d-83fc-8382874a5cb9"
                "translatorType": 8
                "label": "DOI Content Negotiation"
                "creator": "Sebastian Karcher"
                "target": null
                "priority": 100
                "lastUpdated": "2023-09-22 10:50:00"
                "browserSupport": "g"
                "minVersion": "5.0"
                "maxVersion": null
                "inRepository": true
            }
            "init": function(info) {...}
            "serialize": function(properties) {...}
            "logError": function(message, type, line, lineNumber, colNumber) {...}
            "itemType": true
        }
    ]
    "type": "search"
    "_entryFunctionSuffix": "Search"
    "Sandbox": {
        "_itemDone": function(translate, item) {...}
        "getOption": function(translate, option) {...}
        "getHiddenPref": function(translate, pref) {...}
        "loadTranslator": function(translate, type) {...}
        "wait": function(translate) {...}
        "done": function(translate, returnValue) {...}
        "debug": function(translate, string, level) {...}
    }
    "ERROR_NO_RESULTS": "No items returned from any translator"
    "setCookieSandbox": function(cookieSandbox) {...}
    "setSearch": function(search) {...}
    "setIdentifier": function (identifier) {...}
    "getTranslators": function() {...}
    "complete": function(returnValue, error) {...}
    "_getParameters": function() {...}
    "_getSandboxLocation": function() {...}
    "_prepareTranslation": function () {...}
    "init": function() {...}
    "setLocation": function(location) {...}
    "setTranslator": function(translator) {...}
    "setHandler": function(type, handler) {...}
    "clearHandlers": function(type) {...}
    "removeHandler": function(type, handler) {...}
    "setTranslatorProvider": function (translatorProvider) {...}
    "incrementAsyncProcesses": function(f) {...}
    "decrementAsyncProcesses": function(f, by) {...}
    "_runHandler": function(type) {...}
    "_getTranslatorsGetPotentialTranslators": async function () {...}
    "translate": function () {...}
    "_translateTranslatorLoaded": function () {...}
    "getProgress": function() {...}
    "resolveURL": function(url, dontUseProxy) {...}
    "_cleanTitle": function (title, itemType) {...}
    "_cleanTags": function(tags) {...}
    "_saveItems": function () {...}
    "_checkIfDone": function() {...}
    "_detect": async function() {...}
    "_detectTranslatorLoaded": async function () {...}
    "_detectTranslatorsCollected": function() {...}
    "_loadTranslator": function () {...}
    "_generateSandbox": function() {...}
    "_attr": function (selector, attr, index) {...}
    "_text": function (selector, index) {...}
    "_innerText": function (selector, index) {...}
    "_debug": function(string, level) {...}
    "_generateErrorString": function (error) {...}
    "_prepareDetection": function() {...}
}

**Comment by northword** [comment]
很奇怪，看起来是正常的，我也不清楚是哪里的原因 🌚

**Comment by whitehorseprince** [comment]
encountered the same issue. console reads:
<img width="639" alt="截屏2024-03-22 18 46 55" src="https://github.com/northword/zotero-format-metadata/assets/102147019/86ac2060-3185-4b7e-a52b-401d7af37850">

**Comment by northword** [comment]
> encountered the same issue. console reads: <img alt="截屏2024-03-22 18 46 55" width="639" src="https://private-user-images.githubusercontent.com/102147019/315981045-86ac2060-3185-4b7e-a52b-401d7af37850.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMTQ2MDYsIm5iZiI6MTcxMTExNDMwNiwicGF0aCI6Ii8xMDIxNDcwMTkvMzE1OTgxMDQ1LTg2YWMyMDYwLTMxODUtNGI3ZS1hNTJiLTQwMWQ3YWYzNzg1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQxMzMxNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NDVmY2M1YjMwZmJmNThlOTJlMDAxY2E2ODMzMGI3ODhkNzNmYWY1M2Y4NjJkMjEyZjE4MmJjYzlmMjk4OWJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SiKjL-bnk8k4-wmpkGEVmJVjWNylVgkczeJOu4mKSVU">

This is an official TRANSLATE warning, and it is basically certain that this warning has nothing to do with this issue. Can you provide debug logs?

-> https://www.zotero.org/support/debug_output , Debug output files instead of ids, thanks
