### ISSUE TITLE
期刊缩写类型

### ISSUE THREAD

**Issue by zepinglee** [northword/zotero-format-metadata#110]
我注意到期刊有“ISO 4 with”和“without dot”两种。我想问一下后者是针对什么样的需求？

CSL 可以去掉字段内容的点（`strip-periods="true"`），但是不能自动添加点。所以对 CSL 来说，最好总是在期刊缩写加点，然后由 CSL 样式根据期刊的要求选择是否去掉点（见 <https://forums.zotero.org/discussion/59093/>）。从这个角度，“ISO 4 without dot”似乎有些多余。

另外建议提供“期刊自动加点”的功能。

**Comment by northword** [comment]
without dot 是来自用户的稀奇古怪的要求，如果去掉这个的话，也可以把 jcr 给去掉？（大致就是去掉点、大写）

自动加点可能不好实现，csl 不知道在哪里加点，插件也同样存在这个问题。

**Comment by zepinglee** [comment]
> without dot 是来自用户的稀奇古怪的要求

我在 issue 中没有搜索到。

> 如果去掉这个的话，也可以把 jcr 给去掉？（大致就是去掉点、大写）

第一次听说 JCR，这没有更详细的介绍？

> 自动加点可能不好实现，csl 不知道在哪里加点，插件也同样存在这个问题。

我想到的是，将 `journalAbbreviation` 每个词跟全名 `publicationTitle` 的词进行对比：（用 Python 表达）

```python
def add_period(word, publicationTitle):
    if not word.endswith('.')
            and word not in publicationTitle.split()  # 不是全名中某个完整的词
            and any([word in part for part in publicationTitle.split()]):  # 是全名中某个词的部分
        word += '.'
    return word

item.journalAbbreviation = ' '.join([add_period(word, publicationTitle) for word in item.journalAbbreviation.split(' ')])
```

**Comment by northword** [comment]
> 我在 issue 中没有搜索到。

没在 Issue；不过可以参考其他插件的类似问题：https://github.com/zoushucai/zotero-journalabbr/issues/3 

> 第一次听说 JCR，这没有更详细的介绍？

JCR 缩写是在 Web of Science 中记录的期刊缩写，通常是 ISO 4 缩写去掉点，然后全大写，例如：https://jcr.clarivate.com/jcr-jp/journal-profile?journal=APPL%20CATAL%20B-ENVIRON&year=2022

![image](https://github.com/northword/zotero-format-metadata/assets/44738481/80d0f2fc-ae12-4ae7-ab88-9af163668cb3)

也同时考虑到部分同学用 JCR 缩写实现一些其他的东西：https://github.com/zoushucai/zotero-journalabbr/issues/6 ，所以我才加了这个选项。

如果这两个选项不妥，（确认没有 CSL 样式需要显示 JCR 缩写或 JCR 缩写可以通过 CSL 由 ISO 缩写生成），那这两个选项是应该去掉的。


> 另外建议提供“期刊自动加点”的功能。

这个是给期刊缩写加点吗？类似 ISO 4 without dot -> ISO 4 with dot 这种？

如果是的话，我觉得是不必要的，目前插件里理工科的 SCI 期刊的缩写基本上是包括了，没包括的也提供了 LTWA 推断，这个推断出来的是带点的，也就是如果用户需要加点，只需要让插件重新检索缩写就好。

**Comment by zepinglee** [comment]
> 没在 Issue；不过可以参考其他插件的类似问题：[zoushucai/zotero-journalabbr#3](https://github.com/zoushucai/zotero-journalabbr/issues/3)

可能该用户不熟悉 CSL。可以忽略这个需求。

> > 第一次听说 JCR，这没有更详细的介绍？
> 
> JCR 缩写是在 Web of Science 中记录的期刊缩写，通常是 ISO 4 缩写去掉点，然后全大写，例如：https://jcr.clarivate.com/jcr-jp/journal-profile?journal=APPL%20CATAL%20B-ENVIRON&year=2022
> 
> 也同时考虑到部分同学用 JCR 缩写实现一些其他的东西：[zoushucai/zotero-journalabbr#6](https://github.com/zoushucai/zotero-journalabbr/issues/6) ，所以我才加了这个选项。
> 
> 如果这两个选项不妥，（确认没有 CSL 样式需要显示 JCR 缩写或 JCR 缩写可以通过 CSL 由 ISO 缩写生成），那这两个选项是应该去掉的。

去点、全大写可以在 CSL 中以 `<text variable="container-title" form="short" strip-periods="true" text-case="uppercase">` 实现。因此 CSL 不需要 JCR 格式。另外我接触过的参考文献样式没有刊名全大写的。

这两个选项会限制 CSL 样式的功能，比如需要缩写加点的格式不能正确输出。所以你再跟 <https://github.com/zoushucai/zotero-journalabbr/issues/6>  对比权衡一下吧。

> 这个是给期刊缩写加点吗？类似 ISO 4 without dot -> ISO 4 with dot 这种？

是的。

> 如果是的话，我觉得是不必要的，目前插件里理工科的 SCI 期刊的缩写基本上是包括了，没包括的也提供了 LTWA 推断，这个推断出来的是带点的，也就是如果用户需要加点，只需要让插件重新检索缩写就好。

你说的有道理。

**Comment by zjlovezyx** [comment]
有期刊缩写的csl格式样本吗，为什么我一直找不到呀帅哥美女们

**Comment by zepinglee** [comment]
> 有期刊缩写的csl格式样本吗，为什么我一直找不到呀帅哥美女们

https://github.com/search?q=repo%3Acitation-style-language%2Fstyles%20text%20variable%3D%22container-title%22%20form%3D%22short%22&type=code

**Comment by zjlovezyx** [comment]
> > 有期刊缩写的csl格式样本吗，为什么我一直找不到呀帅哥美女们
> 
> https://github.com/search?q=repo%3Acitation-style-language%2Fstyles%20text%20variable%3D%22container-title%22%20form%3D%22short%22&type=code

可是我用了其中的某一个样本，还是实现不了期刊的简写，它在word中显示的还是期刊的全名。对了帅哥，你看下你的谷歌邮箱，我给你发了我出现的问题情况。

**Comment by zepinglee** [comment]
> 可是我用了其中的某一个样本，还是实现不了期刊的简写，它在word中显示的还是期刊的全名。对了帅哥，你看下你的谷歌邮箱，我给你发了我出现的问题情况。

需要在文献的原始数据（`journalAbbreviation` 字段）填写期刊的缩写。

这个插件可以自动填写大部分期刊。

**Comment by northword** [comment]
请认真看首页的自述文档，有链接。https://github.com/northword/zotero-format-metadata?tab=readme-ov-file#install

**Comment by zjlovezyx** [comment]
> 请认真看首页的自述文档，有链接。https://github.com/northword/zotero-format-metadata?tab=readme-ov-file#install

非常感谢！我找到了! 👍
