### ISSUE TITLE
[Bug] 仅当姓名全大写或全小写时执行大写转换

### ISSUE THREAD

**Issue by northword** [northword/zotero-format-metadata#111]
目前的方法可能会将部分姓名（比如下面的例子）错误地转为大写。按照 [APA 的要求](https://apastyle.apa.org/style-grammar-guidelines/references/elements-list-entry) 姓名的大小写应遵循本人的偏好。建议限制范围，比如仅当姓（或名）为全大写或全小写时进行转换。

1. 部分西方人名的 particle，比如“van der Waal, P. N.”、“d’Aubignac”、“Jean de La Fontaine”。
2. 有的阿拉伯人的姓以小写字母开头，比如“ʿAlāʾ al-Aswānī”。

_Originally posted by @zepinglee in https://github.com/northword/zotero-format-metadata/issues/47#issuecomment-1873393689_

**Comment by zepinglee** [comment]
我又试了一下，发现只有“van der Waal”和“Jean de La Fontaine”会分别被错误地转为“Van Der Waal”和“Jean De La Fontaine”，“d’Aubignac”和“al-Aswānī”保持不变。这是因为 `Zotero.Ultilities.capitalizeName` 仅转换全大写或全小写的 word（`part.toUpperCase() === part || part.toLowerCase() === part`）。

我建议将这一条件进一步限制为“`lastName`（或 `firstName`）为全大写或全小写”。

https://github.com/zotero/utilities/blob/9c89b23153ce621ed0f1d581a5e32248704c6fb7/utilities.js#L199-L217

**Comment by northword** [comment]
```ts
    apply(item: Zotero.Item): Zotero.Item | Promise<Zotero.Item> {
        const creators = item.getCreators();

        for (const creator of creators) {
            creator.firstName =
                isFullUpperCase(creator.firstName!) || isFullLowerCase(creator.firstName!)
                    ? Zotero.Utilities.capitalizeName(creator.firstName!.trim())
                    : creator.firstName;
            creator.lastName =
                isFullUpperCase(creator.lastName!) || isFullLowerCase(creator.lastName!)
                    ? Zotero.Utilities.capitalizeName(creator.lastName!.trim())
                    : creator.lastName;
        }
        item.setCreators(creators);
        return item;
    }
```

**Comment by zepinglee** [comment]
> ```ts
>     apply(item: Zotero.Item): Zotero.Item | Promise<Zotero.Item> {
>         const creators = item.getCreators();
> 
>         for (const creator of creators) {
>             creator.firstName =
>                 isFullUpperCase(creator.firstName!) || isFullLowerCase(creator.firstName!)
>                     ? Zotero.Utilities.capitalizeName(creator.firstName!.trim())
>                     : creator.firstName;
>             creator.lastName =
>                 isFullUpperCase(creator.lastName!) || isFullLowerCase(creator.lastName!)
>                     ? Zotero.Utilities.capitalizeName(creator.lastName!.trim())
>                     : creator.lastName;
>         }
>         item.setCreators(creators);
>         return item;
>     }
> ```

LGTM.
