### ISSUE TITLE
[Feature Request] 作者信息中连接符(‐)的删除

### ISSUE THREAD

**Issue by yuemingyutianxia** [northword/zotero-format-metadata#112]
### Describe the feature

你好，我最近在使用zotero时发现，有一部分作者信息中会出现连接符(‐)，但有一些不会出现。我发现连接符(‐)的出现是跟随在文献的原始数据中。我想可不可以添加这样的功能，通过Linter批量的修改连接符(‐)。
![image](https://github.com/northword/zotero-format-metadata/assets/49197571/0c2eb6ba-919f-4141-885d-38d269f8ecb4)
![image](https://github.com/northword/zotero-format-metadata/assets/49197571/94d9ada5-9d58-4f48-8d37-dbff31b3012e)

**Comment by northword** [comment]
duplicate of #61
