### ISSUE TITLE
[Feature Request] 统一学位论文类型

### ISSUE THREAD

**Issue by zepinglee** [northword/zotero-format-metadata#132]
### Describe the feature

原帖在  <https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/commit/0210f6621ff12c6fb791ec5b9e698d23712bd45f#commitcomment-137770113>。

1. 一些早期的 translator 抓取的“学位论文类型”为“博士”或“硕士”，不符合 Zotero 的要求（参考 [FAQ](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/wiki/FAQ#%E4%B8%BA%E4%BD%95%E5%AD%A6%E4%BD%8D%E8%AE%BA%E6%96%87%E7%B1%BB%E5%9E%8B%E6%98%BE%E7%A4%BA%E5%8D%9A%E5%A3%AB%E8%80%8C%E4%B8%8D%E6%98%AF%E5%8D%9A%E5%A3%AB%E5%AD%A6%E4%BD%8D%E8%AE%BA%E6%96%87)），需要补上“学位论文”。
2. 一些 CSL 样式需要输出该字段，建议将空的 `thesisType` 填写默认的 `博士学位论文` 或 `Doctoral dissertation`。
3. 将 `thesisType` 的大小写统一为 sentence case，例如 `Ph.D. dissertation`, `Master’s thesis`，方便 CSL 按需求处理。

### Additional context

```js
    let genre = item.getField('type', false, true);
    let newGenre = genre;

    if (item.itemType === 'thesis') {
        if (!genre) {
            newGenre = 'Doctoral dissertation';
            if (isChinese(item.getField('title'))) {
                newGenre = '博士学位论文';
            }
        }
        if (newGenre === '博士' || newGenre === '硕士') {
            newGenre = newGenre + '学位论文';
        } else if (newGenre === 'Dissertation' || newGenre === 'Thesis') {
            newGenre = 'Doctoral dissertation';
        }
    }
    if (newGenre) {
        newGenre = Zotero.Utilities.capitalize(newGenre);
        newGenre = newGenre.replace(' Dissertation', ' dissertation');
        newGenre = newGenre.replace(' thesis', ' thesis');
    }
```

**Comment by zepinglee** [comment]
呃……跟 #131 发重了。

**Comment by zepinglee** [comment]
> 这样是否会有不妥？我觉得如果一篇论文没有填类别，且插件不能准确获取类别的时候，最好应保持留空，让用户在检查参考文献表时候判断补充，而不是给出假值。

也行。

> 硕士 -> 硕士学位论文 博士 -> 博士学位论文 Dissertation -> Doctoral dissertation Ph.D. -> Doctoral dissertation thesis -> Master thesis master -> Master thesis
> 
> 这样应该就可以？（应该么有其他常见的乱七八糟的词了吧）

那就去掉 `Dissertation -> Doctoral dissertation` 和 `thesis -> Master thesis` 吧，dissertation 和 thesis 是同义词，没有硕士博士之分。

**Comment by northword** [comment]
> dissertation 和 thesis 是同义词，没有硕士博士之分。

我查到的一些资料里显示这个是有区分的：

![image](https://github.com/northword/zotero-format-metadata/assets/44738481/347c29db-60ca-4e89-b4ed-2a763d7927f2)


https://www.uopeople.edu/blog/dissertation-vs-thesis/#:~:text=The%20biggest%20difference%20between%20a,research%20and%20then%20perform%20analysis.

https://www.gcu.edu/blog/doctoral-journey/thesis-vs-dissertation

**Comment by zepinglee** [comment]
MW 的解释并没有特别明显的差异。

https://www.merriam-webster.com/dictionary/dissertation

https://www.merriam-webster.com/dictionary/thesis

可能 dissertation 更特指博士学位论文，而 thesis 是个通用的词。Zotero 的文献类型也用的是 `thesis` 这个词。

**Comment by northword** [comment]
> 那就去掉 `Dissertation -> Doctoral dissertation` 和 `thesis -> Master thesis` 吧

那可以去掉 thesis -> Master thesis ，保留 Dissertation -> Doctoral dissertation
