### ISSUE TITLE
[Bug] Compatibility with new UI of Zotero 7 beta 55

### ISSUE THREAD

**Issue by northword** [northword/zotero-format-metadata#133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: 
- Zotero Version: 7-beta55
- Addon Version: 1.9.1

### Describe the bug

- [ ] 富文本工具框失效
- [ ] 去除首选项页面的一级标题

**Comment by zepinglee** [comment]
顺便请教一下，他们 Zotero 7 是在哪个仓库/分支下开发的？我在 <https://github.com/zotero/zotero> 中没找到相关的分支或 tag。

**Comment by northword** [comment]
就是在 zotero/zotero 主分支，只不过官方应该有一个私有仓库，Z7 的开发进度并不对社区公开，决定公开的时候才会把commit同步过来。
