### ISSUE TITLE
[Feature Request] 希望可以更新摘要

### ISSUE THREAD

**Issue by llity** [northword/zotero-format-metadata#142]
### Describe the feature

新版 Z7 只能更新info信息，摘要没法更新。

**Comment by northword** [comment]
如果数据源包含摘要，应可以正常更新。

数据源是 doi.org 和 crossref。

**Comment by llity** [comment]
确实是的，可能被拦截了。访问DOI，被重定向到https://www.sciencedirect.com/，打开里面的文章能看见摘要。
![image](https://github.com/northword/zotero-format-metadata/assets/11771112/30c08e46-050e-43af-ab29-f1073b7985c2)

**Comment by northword** [comment]
与此页面无关，你可以访问数据库的接口：

```
https://crossref.org/openurl/?pid=myemail@crossref.org&format=unixref&id=在这里输入DOI不加网址前缀&noredirect=true
```

例如 

```
https://crossref.org/openurl/?pid=myemail@crossref.org&format=unixref&id=10.1016/j.apcata.2012.10.036&noredirect=true
```

如果里面有摘要，就可以正常更新。

**Comment by llity** [comment]
这个是有的吧。更新没摘要。
`https://crossref.org/openurl/?pid=myemail@crossref.org&format=unixref&id=10.1016/j.cca.2018.07.004&noredirect=true`

**Comment by northword** [comment]
这里面没有摘要啊？你截个图我看看呢？

**Comment by llity** [comment]
获取不到摘要
![image](https://github.com/northword/zotero-format-metadata/assets/11771112/62c711bf-cb71-47ec-bbdd-ff09f075ecb4)

**Comment by northword** [comment]
> 这个是有的吧。更新没摘要。
> `https://crossref.org/openurl/?pid=myemail@crossref.org&format=unixref&id=10.1016/j.cca.2018.07.004&noredirect=true`

这是数据库，数据库里不包含摘要，我也无法解决。

插件只是从数据库获取数据，数据库中没有的数据无法获取。

第一条回复中我提到了，插件获取数据的来源是doi和crossref，请区分这两个数据库和期刊出版商本身。期刊出版商太多了，插件无力适配。

**Comment by northword** [comment]
> 这个是有的吧。更新没摘要。
> `https://crossref.org/openurl/?pid=myemail@crossref.org&format=unixref&id=10.1016/j.cca.2018.07.004&noredirect=true`

这个链接你可以直接访问，有就是有，插件就可以更新。
