### ISSUE TITLE
[Feature Request] 批量处理条目时，跳过长时间无响应的条目，并标记tag

### ISSUE THREAD

**Issue by Qiujv** [northword/zotero-format-metadata#147]
### Describe the feature

新装的这个插件，想要把文献库里以往的条目信息补全一下，但是总是卡在某个条目。也不知道是哪一个，只能一条一条手动点击更新。最好是每个条目的处理时间增加一个timeout，超时没有处理完的标一个特殊tag，方便之后找出来单独处理。

**Comment by northword** [comment]
理论上不会出现一个条目长时间无响应，所有需要耗时的都是有网络请求的，Zotero 有默认的超时时间，超时的会视为失败。

你可以提供无响应的条目和复现步骤吗？

关于自动跳过并 tag，可以考虑加上。

**Comment by Qiujv** [comment]
DOI 10.7693/wl20230606 ，《物理》杂志的一篇文章，在线连接在这里 https://wuli.iphy.ac.cn/cn/article/doi/10.7693/wl20230606 。添加到仓库后，右键条目 - linter - Retrieve Fields via DOI - Retrieve all fields and lint 点击后弹窗显示 Progressing... 就没有进展了，吃个饭回来弹窗还在，期间Zotero界面正常。我的Zotero版本 7.0.0-beta.58+2665090aa (64-bit) ，插件版本 1.12.0。我猜可能是中文条目的缘故。

**Comment by northword** [comment]
> 我猜可能是中文条目的缘故。

是的，是 chinadoi.cn 不可用导致。
