### ISSUE TITLE
部分文献语言识别错误[Bug] 

### ISSUE THREAD

**Issue by LiuJ00** [northword/zotero-format-metadata#156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: 13.6.4
- Zotero Version: 7.0.0-beta.63+965149fe0
- Addon Version:1.12.2

### Describe the bug

部分文献在执行时，语言识别错误。（貌似跟期刊没有关系，相同期刊有的识别准确，有的不正确）
<img width="296" alt="CleanShot 2024-02-26 at 17 02 25@2x" src="https://github.com/northword/zotero-format-metadata/assets/136417116/e1c5e460-ecc8-43e2-968a-496c6ea9ebbc">
<img width="287" alt="CleanShot 2024-02-26 at 17 03 54@2x" src="https://github.com/northword/zotero-format-metadata/assets/136417116/eedb7b55-f92c-42c5-8d29-3e09383d1bb1">
<img width="296" alt="CleanShot 2024-02-26 at 17 04 30@2x" src="https://github.com/northword/zotero-format-metadata/assets/136417116/de592cff-da40-469e-aa64-effc706e8972">
<img width="314" alt="CleanShot 2024-02-26 at 17 05 31@2x" src="https://github.com/northword/zotero-format-metadata/assets/136417116/bc88f4e8-6857-4c3b-8067-42af580a2198">
<img width="289" alt="CleanShot 2024-02-26 at 17 11 36@2x" src="https://github.com/northword/zotero-format-metadata/assets/136417116/ce1338a4-d7ab-49e8-8736-f401702d509c">

**Comment by northword** [comment]
启用语言限制。

![image](https://github.com/northword/zotero-format-metadata/assets/44738481/6076a134-2d96-4b4e-8d6a-d9bb628050ae)

这是默认启用的，请确认没有关闭。

**Comment by LiuJ00** [comment]
感谢大佬更新及时
