### ISSUE TITLE
[Feature Request] 通过 semantic scholar 更新元数据

### ISSUE THREAD

**Issue by northword** [northword/zotero-format-metadata#161]
### Describe the feature

您好，很感谢您开发的这个插件！现在很大的问题在于绝大部分刊登在arxiv上文章都不会更新自己发表在其它会议或期刊上的新信息，最多只留下一个comment。目前CS领域比较主流的是从 semantic scholar 上获取更新的信息，不知道您可否考虑加入进来？利用 semantic scholar api 可以查询发表在 arxiv 上的预印本是否已经发表论文（虽然没有囊括所有，但胜在简单可靠，且更新相对及时）

例子：
```
https://api.semanticscholar.org/graph/v1/paper/ArXiv:1705.07874?fields=publicationVenue,externalIds,journal,publicationTypes
``` 

### Additional context

_Originally posted by @invisprints in https://github.com/northword/zotero-format-metadata/issues/57#issuecomment-1988703517_

**Comment by northword** [comment]
插件将首先从 arxiv 获取是否有正式发表的 doi 信息，如果没有，则向 semantic scholar 请求数据。

为了保证不被速率限制，你可能需要在插件设置中填写 semantic scholar token。

由于没有大量样本做测试，在遇到问题时烦请继续报告一个 issue。

**Comment by invisprints** [comment]
感谢作者！不过目前还是无法顺利更新，就拿上面的文章为例 https://arxiv.org/abs/2107.07511
用 Zotero Connect 从浏览器抓取后，DOI、仓库、存档ID、网址、其它等字段都有元数据信息：
```
仓库: arXiv
存档ID: arXiv:1705.07874
DOI: 10.48550/arXiv.1705.07874
网址: http://arxiv.org/abs/1705.07874
其它: arXiv:1705.07874 [cs, stat]
```

Zotero 控制台的信息如下
```
HTTP GET https://api.semanticscholar.org/graph/v1/paper/DOI:10.48550/arXiv.1705.07874?fields=publicationTypes,title,authors,abstract,externalIds,url,venue,publicationVenue,publicationDate,journal failed with status code 404: {"error":"Paper with id DOI:10.48550/arXiv.1705.07874 not found"
```
可以看出 Linter 优先抓取 DOI 的信息，而且格式似乎也没对，DOI 类文献不包含 `DOI` 这个关键字，[SS API 说明](https://www.semanticscholar.org/product/api/tutorial#using-paper-search-with-external-ids)
不过大部分 Arxiv 类预印本通过此类方式也无法更新，还是按照 https://api.semanticscholar.org/arXiv:1705.10311 获取成功率最高

**Comment by northword** [comment]
> 可以看出 Linter 优先抓取 DOI 的信息，而且格式似乎也没对，DOI 类文献不包含 DOI 这个关键字，[SS API 说明](https://www.semanticscholar.org/product/api/tutorial#using-paper-search-with-external-ids)

根据文档，带上 `DOI` 也是正确的；

![image](https://github.com/northword/zotero-format-metadata/assets/44738481/5ef11cac-3975-4f82-aed0-5ff78ba07748)

![image](https://github.com/northword/zotero-format-metadata/assets/44738481/41cf82e9-96b4-47b4-aa20-53d402212d0e)

你所给出的这篇应该是预印本 DOI 在 ss 中没有记录，我应该可以调整一下顺序，优先使用 arxiv id 进行请求。

今天晚点改个版本再试试。
