### ISSUE TITLE
[Bug] 根据标识符更新元数据提示错误

### ISSUE THREAD

**Issue by TIANTIANSTUDY** [northword/zotero-format-metadata#166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 11 23H2
- Zotero Version: 7.0.0-beta.63+52856ae69 (64-bit)
- Addon Version: 1.15.1

### Describe the bug

根据标识符更新元数据时提示错误
![1711435284304](https://github.com/northword/zotero-format-metadata/assets/42690087/3f9af143-db8a-4d14-980b-1afdb7406467)

**Comment by northword** [comment]
请提供被更新条目的信息（在条目上右击，选择导出条目，格式 Zotero RDF）和操作步骤。

**Comment by TIANTIANSTUDY** [comment]
> 请提供被更新条目的信息（在条目上右击，选择导出条目，格式 Zotero RDF）和操作步骤。
操作步骤：
![image](https://github.com/northword/zotero-format-metadata/assets/42690087/12e72940-4305-47f0-95e9-13b62f3a666e)
条目信息：[reference.zip](https://github.com/northword/zotero-format-metadata/files/14754150/reference.zip)
我文献库所有文献更新元数据基本都提示错误，应该不是单个条目的问题。

**Comment by northword** [comment]
初步判断是生产模式下构建插件弃用的压缩代码导致的，请尝试 1.15.2 版本是否仍有问题。
