### ISSUE TITLE
[Bug] 期刊简写错误

### ISSUE THREAD

**Issue by ramonmi** [northword/zotero-format-metadata#167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 11 23H2
- Zotero Version: 7.0.0-beta.68+c31a40c74 (64-bit)
- Addon Version: 1.15.3

### Describe the bug

期刊Physical Chemistry Chemical Physics的简写应为Phys. Chem. Chem. Phys.，但最近Linter --> Look up journal abbreviations， 得到的结果为PCCP，如图。
![Video_20240327150348-ezgif com-video-to-gif-converter](https://github.com/northword/zotero-format-metadata/assets/105206348/98581e7c-749f-459b-8419-17fe74cad5dc)

**Comment by northword** [comment]
感谢反馈，已在 1.15.4 修复。
