### ISSUE TITLE
[Bug] 标题中专有名词在转换后首字母没有大写

### ISSUE THREAD

**Issue by museburg** [northword/zotero-format-metadata#171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 11
- Zotero Version: 7.0.0-beta.68+c31a40c74
- Addon Version: 1.16.2

### Describe the bug

文献标题中的国家名、地名等专有名词在转换后首字母没有大写。地球科学领域有很多文献标题都含有地名，如果一一手动修改比较麻烦。
比如这篇文章，原始metadata如下：
![image](https://github.com/northword/zotero-format-metadata/assets/59810944/ba20565e-836a-4e6b-843c-64abcbd77e17)
选择Linter--Lint and Fix转换后，metadata如下：
![image](https://github.com/northword/zotero-format-metadata/assets/59810944/be93efde-2d17-4c38-9293-b3c17fe692d3)

好像没看到有人提出过类似问题，所以来提一下。所有含地名的文献标题在转换后都会出现这个问题，希望能优化一下。谢谢！

**Comment by northword** [comment]
国名：duplicate of #33 

地名是城市名吗？可以举一些例子不？

如 #33 ，在你的研究领域中，国名除了在 in 、 of 之后，还会在其他位置出现吗？

（我们需要有一套逻辑去识别他到底是不是国名，否则做陶瓷材料等的同学可能就会收到影响）

**Comment by museburg** [comment]
> 国名：duplicate of #31
> 
> 地名是城市名吗？可以举一些例子不？
> 
> 如 #31 ，在你的研究领域中，国名除了在 in 、 of 之后，还会在其他位置出现吗？
> 
> （我们需要有一套逻辑去识别他到底是不是国名，否则做陶瓷材料等的同学可能就会收到影响）

你好，谢谢回复！

地名包括大洲（Asia）、海洋（Pacific）、国家名（China）、城市名（Beijing）、大江大河（Yangtze River）、大地形（Tibetan Plateau）等，常见的出现位置除了in、of之后，还有over之后，或者介词+方位词之后，比如：
- over the eastern **Mediterranean**
- over the southwestern **Tibetan Plateau** 
- over the southern slope of **Tibetan Plateau**
- in southern **China**
- in **Tianjin**, **China** 

还有一个常见的位置是在名词之前，比如：
- **Atlantic** origin of the increasing **Asian** westerly jet interannual variability
- Roles of the **Tibetan Plateau** vortices in the record Meiyu rainfall in 2020
- Reflections on the catastrophic 2020 **Yangtze River** basin flooding in southern China
- Historic **Yangtze** flooding of 2020 tied to extreme **Indian Ocean** conditions
- Locally opposite responses of the 2023 **Beijing–Tianjin–Hebei** extreme rainfall event to global anthropogenic warming

另外还有月份、星期这类词转换后首字母也没有大写，比如这篇文章：
Attribution of the **August** 2022 Extreme Heatwave in Southern **China**: Role of Dynamical and Thermodynamical Processes
就会变成：
Attribution of the **august** 2022 extreme heatwave in southern **china**: role of dynamical and thermodynamical processes

**Comment by northword** [comment]
## 部分数据

### 国家与城市/行政区

- 国家名：http://www.ting.com.tw/agent/ecountry.htm ，https://github.com/BG7ZAG/country-code
- 城市名：https://github.com/datasets/world-cities/blob/master/data/world-cities.csv

必须在介词后。

### 地理

- 大洲：下
- 大洋：下
- 江河：https://en.wikipedia.org/wiki/List_of_river_systems_by_length
- 山川：https://en.wikipedia.org/wiki/List_of_highest_mountains_on_Earth#External_links
- 大地形：未找到

```csv
亚洲	Asia
欧洲	Europe
非洲	Africa
北美洲	North America
南美洲	South America
大洋洲	Oceania
南极洲	Antarctica
```

全是专有词，可以直接给大写。

```csv
太平洋	the Pacific Ocean
大西洋	the Atlantic Ocean
印度洋	the Indian Ocean
北冰洋	the Arctic Ocean
```

大洋，中间的词是否在所有情况下都是专有的（例如非地学领域），如果是，可以不考虑 `the ocean` 直接将其大写。

所有多个词的还好，如果是单个词的，就需要考虑是否会对其他领域造成影响。

这一块，尤其是山川河流与地形，显然我查到的是不全的，你们领域是否有整理的英文名列表呢？

没有的话就只能添加这些，其他的使用自定义术语表了。

### 日期

- 节日：https://english.cool/festival-english/
- 月份：下
- 星期：下

```csv
一月,January,Jan.
二月,February,Feb.
三月,March,Mar.
四月,April,Apr.
五月,May,
六月,June,Jun.
七月,July,Jul.
八月,August; Aug.
九月,September,Sep.
十月,October,Oct.
十一月,November,Nov.
十二月,December,Dec.
```

月份中，由于 `may` 可以是一个虚词，因此必须在介词后。

```csv
星期一,Monday,Mon.
星期二,Tuesday,Tues.
星期三,Wednesday,Wed.
星期四,Thursday,Thur./Thurs.
星期五,Friday,Fri.
星期六,Saturday,Sat.
星期日,Sunday,Sun.
```

星期中，似乎都是专有词，可以直接替换，保险起见也须在介词后。

## 介词匹配

> todo

**Comment by fredericky123** [comment]
补充一个，能否增加一些常见人名，星球名，比如我们领域会用比喻的修辞在题目里，提到一些国外谚语，如：
Jacks of all trades and masters of none
How Cinderella became a queen: theorizing radical status change

I left Venus and came back to Mars: temporal focus congruence in dyadic relationships following maternity leave

**Comment by northword** [comment]
@fredericky123 

> 另，补充几个企业类缩写名词：SME, MNE, FDI

这种全大写的缩写词目前就不会被小写——在非全大写的标题中的全大写单词会保持原样，如果这些词被转为小写，请报告一个新的 bug issue。

> Internet

简单看了下这个词的首字母是否大写似乎存在争议，如果没有其他手段确定是否应为大写，这种词建议使用自定义术语。

**Comment by fredericky123** [comment]
目前没有bug哈
那Internet自定义也方便，感谢感谢

**Comment by northword** [comment]
大江河大地形由于我收集到的数据明显不全，且同一名称有多种写法（似乎是），所以只内建了几个，可以通过自定义术语实现，如果有收集好的同学也可以发出来，用的人多的话就内建进插件。

星球名目前仅收集了太阳系九大行星。

城市名仅内建了各国家的首都。

**Comment by fredericky123** [comment]
请问哪里可以下载到常用的国名、地名等
