### ISSUE TITLE
[Help?] Semantic Scholar support

### ISSUE THREAD

**Issue by jeff47** [northword/zotero-format-metadata#173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 11
- Zotero Version: 7.0.0-beta.68+c31a40c74 (64-bit)
- Addon Version: 1.16.2

### Describe the bug

Can you add some info on what the Semantic Scholar token is supposed to do, and how we find it?

**Comment by northword** [comment]
The semantic scholar token is used for the "retrieve field data based on identifiers" function, and is used by the plugin to increase the rate limit when requesting field info from the semantic scholar for preprint items.

We will add a description of what this option does and how to find it in the settings pane in the next version.
