### ISSUE TITLE
[Feature Request]  Apply case rules to tags?

### ISSUE THREAD

**Issue by jeff47** [northword/zotero-format-metadata#174]
### Describe the feature

Zotero ends up creating lot of duplicate tags that are different only by the capitalization.  I'd be willing to sacrifice "correctness" of some abbreviations of technical terms to just have linter make all my tags lower case for consistency!

**Comment by northword** [comment]
Thanks for the suggestion!

I'm not sure if this feature is necessary to add to this plugin, the primary purpose of this plugin is to keep the field data accurate and standardized to ensure that the bibliography can be output correctly.

I do have ideas for managing tags, but I don't have enough time in the near future.

Until then, you can use [this script](https://github.com/coskun-kilinc/zotero-tag-modifier) to adjust the case of existing tags and the [Actions & tags plugin](https://github.com/windingwind/zotero-actions-tags) to adjust the tags of new items that are added.

**Comment by jeff47** [comment]
Agreed, this is easily done using the the [Action Tags](https://github.com/windingwind/zotero-actions-tags) plugin, and can be customized in that implementation as well.
