### ISSUE TITLE
[Bug] Linter1.16.3自定义期刊缩写不支持选择json格式文件

### ISSUE THREAD

**Issue by aaronkhq** [northword/zotero-format-metadata#178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: MacOs Sonoma 14.1.1 (23B81)
- Zotero Version: 7.0.0-beta.72+128a540af
- Addon Version: 1.16.3

### Describe the bug

如题,  Linter1.16.3自定义期刊缩写不支持选择json格式文件. 

![image](https://github.com/northword/zotero-format-metadata/assets/65768952/f1383515-a3f1-4dfb-8a65-78df9d1c8594)

实测了一下, 1.15.4版本的可以选择json格式的自定义期刊缩写的文件.
可能是增加对csv的支持后引起的bug.

谢谢作者amazing的开发!!!

**Comment by northword** [comment]
在弹出的文件选择框右下角切换文件类型为json

**Comment by northword** [comment]
![image](https://github.com/northword/zotero-format-metadata/assets/44738481/e27562a0-12cb-40b0-8041-d0480ef9fb7f)

**Comment by aaronkhq** [comment]
非常感谢如此迅速的回复!!

但是,很可惜,还是无法选中

<img width="800" alt="image" src="https://github.com/northword/zotero-format-metadata/assets/65768952/e4e85d69-df8d-48bd-a88a-3dc95ca4dc90">

**Comment by aaronkhq** [comment]
太棒了!!太高效了!!谢谢!!点赞

**Comment by ramonmi** [comment]
哈哈，我之前也遇到了，选所有文件才可以看到json文件。感谢修复！

**Comment by aaronkhq** [comment]
mac上选择所有文件也不行,我之前试过哈哈哈
