### ISSUE TITLE
[Feature Request] Title case and sentence case

### ISSUE THREAD

**Issue by northword** [northword/zotero-format-metadata#18]
## option

- [ ] batch convert title case to sentence case
- [ ] convert on item added
- [ ] 连字符或冒号后是否需要大写
- [ ] fullowing rules, each
- [ ] 已处理过的，不再处理
    - 通过添加标签
    - 通过识别是否含有富文本标签

是否有必要提供 batch sentence case to title case 选项

## rules for converting title case to sentence case

split a string by space, for per word:

- 虚词，使其小写
- 全为小写，跳过
- 有 1 个大写字母，且为首字母
    - 含有数字，保持
    - 为元素周期表元素之一，保持
    - 含有其他非字母非数字字符如 `-`, `\`, `/`, `·`, `+` 保持
    - 含有富文本 HTML 标签
    - 以上全否：小写
- 有 1 个大写字母，且不为首字母，保持
- 有多个大写字母，保持

- 处于 `<span class="no case">` 中，保持

**Comment by northword** [comment]
08cc28b72b7a938c8a91501d883db31b0c5602c9

**Comment by northword** [comment]
国家名   在 in of 等介词后时，认为其是国家名而不是普通名词，给大写

**Comment by zepinglee** [comment]
建议使用 [UAX#29](https://unicode.org/reports/tr29/) 进行分词，可以处理更复杂的情况，比如像en dash, em dash 等其他标点符号，还有像撇号这样有歧义的符号（“Foo’s ‘bar’.”）。

另外“全为小写，跳过”是指跳过整个标题的转换吗（而不是只跳过这个词）？其实如果某个词既不是虚词又是全小写，可以判定整个标题已经是 sentence case 了。像 BBT 的“Sentence-case titles on import”功能的默认选项是“yes, but try to exclude already-sentence-cased titles”。当然，像“History of Internet”这样的标题无法按此判断，可能会被错误地转为“History of internet”。

我之前在 citeproc-lua 中实现了 BibTeX to CSL-JSON 的转换，前者要求题名为 title case，后者使用 sentence case。所以跟你的情况有些类似。

**Comment by northword** [comment]
这个方案已经过时了，五个多月前 bbt 作者把他的代码提交到了 [Zotero.Utilities](https://github.com/zotero/utilities/blob/9c89b23153ce621ed0f1d581a5e32248704c6fb7/utilities.js#L121), 目前插件的这个功能只是在这些代码的基础上加了个 化学元素识别。

官方的不能加化学式，是因为部分小语种的虚词与化学元素一样，会造成干扰。

见：https://github.com/zotero/utilities/pull/26 ，https://github.com/zotero/utilities/pull/27

**Comment by zepinglee** [comment]
> 这个方案已经过时了，五个多月前 bbt 作者把他的代码提交到了 [Zotero.Utilities](https://github.com/zotero/utilities/blob/9c89b23153ce621ed0f1d581a5e32248704c6fb7/utilities.js#L121), 目前插件的这个功能只是在这些代码的基础上加了个 化学元素识别。
> 
> 官方的不能加化学式，是因为部分小语种的虚词与化学元素一样，会造成干扰。
> 
> 见：[zotero/utilities#26](https://github.com/zotero/utilities/pull/26) ，[zotero/utilities#27](https://github.com/zotero/utilities/pull/27)

我比较信任 BBT 的作者，那就没问题了。
