### ISSUE TITLE
[Feature Request] 在编辑Title格式的工具条中，可否加入”小型大写字母“的选项

### ISSUE THREAD

**Issue by Fucose** [northword/zotero-format-metadata#180]
### Describe the feature

糖化学领域经常会用到小型大写字母（并非下标，或者小字号的大写字母）
能否增加一个设置小型大写字母的按钮，插入标签`<span style="font-variant:small-caps;"></span>`

**Comment by northword** [comment]
将在下个版本支持
我倒是知道这个格式，就是一直不知道哪个领域才用的到就没做
