### ISSUE TITLE
[Bug] 更新zotero beta77后，全部功能失效

### ISSUE THREAD

**Issue by luxaug** [northword/zotero-format-metadata#182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Win11
- Zotero Version: 7.0.0-beta.77
- Addon Version: 1.16.4

### Describe the bug

更新zotero7至beta77后，linter的功能失效，即便只打开linter一个插件，也无效。始终显示【正在处理中，请耐心等待】

**Comment by northword** [comment]
Upstream bug, temporarily fixed in 1.16.5.
