### ISSUE TITLE
[Bug] 期刊名称中的The被直接剔除

### ISSUE THREAD

**Issue by hzwlux** [northword/zotero-format-metadata#188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 11
- Zotero Version: 7.0.0-beta.79
- Addon Version: 1.16.9

### Describe the bug

期刊名称为：The Accounting Review，但是被自动替换成Accounting Review。虽然缩写时确实需要省略The，但是全称是不省略的。

**Comment by northword** [comment]
https://jcr.clarivate.com/jcr-jp/journal-profile?journal=ACCOUNT%20REV&year=2022

Web of Science 是 `Accounting Review`，包括 JabRef 记录的也是 `Accounting Review`，虽然官网确实是 `The Accounting Review` 以哪个为准好呢？
