### ISSUE TITLE
[Bug] 学位论文的语言、地点在添加条目时不自动更新；学位论文的语言更新有误；国防科大的地点无法更新

### ISSUE THREAD

**Issue by Phoebe-test** [northword/zotero-format-metadata#189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 10 22H2 家庭中文版
- Zotero Version: 7.0.0-beta.81+721f54fe4 (64-bit)
- Addon Version: 1.16.10

### Describe the bug

1. 学位论文的`语言`、`地点`在添加条目时不自动更新
- 如图所示：
![PixPin_2024-05-26_06-16-10](https://github.com/northword/zotero-format-metadata/assets/103734097/51fab48e-208b-4711-93de-61f35944262a)
2. 右键手动**“Lint并修复”**后，语言变更有误
- 如图所示：
![PixPin_2024-05-26_06-19-29](https://github.com/northword/zotero-format-metadata/assets/103734097/4f74dd90-649f-42c0-97c1-b5fa34f85220)
3. 右键手动**“Lint并修复”**后，**国防科学技术大学**的`地点`不更新
- 相同问题：#126 
- 如图所示：
![PixPin_2024-05-26_06-20-29](https://github.com/northword/zotero-format-metadata/assets/103734097/979563b8-bb1d-4f1a-9f8c-d50b3aa32e5c)
- 推测原因：国防科大在不同时期有不同称呼，因此导致无法匹配，但测试了三个名字都无法更新`地点`
![PixPin_2024-05-26_06-25-43](https://github.com/northword/zotero-format-metadata/assets/103734097/baa3d6c6-8d49-42f1-a953-68e0d146f7d6)

**Comment by northword** [comment]
烦请截图设置页。

**Comment by Phoebe-test** [comment]
感谢大佬拨冗垂阅，有关设置如图
![PixPin_2024-05-26_13-46-17](https://github.com/northword/zotero-format-metadata/assets/103734097/c7dcb0a9-16a0-4f16-9dc1-23341ac7bf04)

**Comment by northword** [comment]
我未能复现你所说的第一点，是否可能存在其他插件干扰的情况？

语言识别错误的请启用“限制识别语言为 简体中文，英文”；

高校地点问题将于下一版本修复。

**Comment by Phoebe-test** [comment]
您好，我在逐项排查插件后，发现是插件[zotero-actions-tags](https://github.com/windingwind/zotero-actions-tags)中，脚本[[Share] Auto-Translate the New Item's Title #107](https://github.com/windingwind/zotero-actions-tags/discussions/107)导致的，将此脚本关闭后就可以在添加条目时自动更新学位论文的`语言`、`地点`了。问题并不是Zotero Connector或茉莉花导致的。

**Comment by northword** [comment]
可能插件之间存在冲突，Zotero 官方目前没有提供有效的控制插件触发顺序的机制。

可以尝试关闭 Linter 的添加条目自动 lint，然后在 Actions 里调用 Linter：

```js
Zotero.Linter.hooks.onLintInBatch("std", item)
```

这个接口在短时间内应该不会作显著改变。

后二者将在下一版本修复。

**Comment by northword** [comment]
:rocket: _This ticket has been resolved in v1.16.11. See [Release 1.16.11](https://github.com/northword/zotero-format-metadata/releases/tag/v1.16.11) for release notes._

**Comment by Phoebe-test** [comment]
> 可能插件之间存在冲突，Zotero 官方目前没有提供有效的控制插件触发顺序的机制。
> 
> 可以尝试关闭 Linter 的添加条目自动 lint，然后在 Actions 里调用 Linter：
> 
> ```js
> Zotero.Linter.hooks.onLintInBatch("std", item)
> ```
> 
> 这个接口在短时间内应该不会作显著改变。
> 
> 后二者将在下一版本修复。

您好，我在 Actions 里没能成功调用 Linter *（已关闭 Linter 的添加条目自动 lint）*，可否麻烦您看一下这样设置是否正确：
![PixPin_2024-05-27_13-39-06](https://github.com/northword/zotero-format-metadata/assets/103734097/d872a715-9ec3-4080-89b1-31c31a78a565)
**数据：**
```js
Zotero.Linter.hooks.onLintInBatch("std", item)
```

非常感谢！

**Comment by northword** [comment]
抱歉我给错了代码，Linter 插件这个接口接收的参数是一个 Zotero.Item[]，代码需要修改为：

```js
return await Zotero.Linter.hooks.onLintInBatch("std", [item])
```

**Comment by Phoebe-test** [comment]
> 抱歉我给错了代码，Linter 插件这个接口接收的参数是一个 Zotero.Item[]，代码需要修改为：
> 
> ```js
> return await Zotero.Linter.hooks.onLintInBatch("std", [item])
> ```

芜湖！可以解决插件之间的冲突了！为大佬献上膝盖！

**Comment by Phoebe-test** [comment]
为了解决Linter与自动翻译脚本之间的冲突，我想了一种[解决方案](https://github.com/windingwind/zotero-actions-tags/discussions/329#discussioncomment-9730887)：
1. 先通过 Action & Tags 运行 [Linter](https://github.com/northword/zotero-format-metadata/issues/189#issuecomment-2132715266) 调整语言字段
2. 再**延时2000毫秒**运行 [Auto-Translate the New Item's Title](https://github.com/windingwind/zotero-actions-tags/discussions/107#discussioncomment-7378390)翻译标题和摘要
