### ISSUE TITLE
[Bug] 自定义标题文本替换的正则表达式失效

### ISSUE THREAD

**Issue by wangfh5** [northword/zotero-format-metadata#191]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

- OS: macOS
- Zotero Version: 7.0.0
- Addon Version: latest

### Describe the bug

使用正则表达式`fermi(?!on)`，匹配fermi并替换为Fermi，但是不匹配fermion，fermions，fermionic等等，测试正常
<img width="801" alt="image" src="https://github.com/northword/zotero-format-metadata/assets/51868839/c84cd5ef-ee0b-42e3-b5d6-aaa7fdb1a0c7">
在csv文件中使用`\`符号包裹正则表达式
<img width="183" alt="image" src="https://github.com/northword/zotero-format-metadata/assets/51868839/6c875358-8215-4976-a6c2-5416990cfbbc">
结果匹配失败，convert to sentence case之后没有将fermi并替换为Fermi（同时fermion也不会被替换为Fermion）
<img width="450" alt="image" src="https://github.com/northword/zotero-format-metadata/assets/51868839/1bf62403-3e1f-4069-92b4-81152bc7fdf9">

**Comment by northword** [comment]
抱歉先前给出了错误的回复，请尝试 `/fermi(?!on)/`

**Comment by wangfh5** [comment]
成功了，感谢回复，建议可以写在设置的提示词里面
