### ISSUE TITLE
[Feature Request] Remove `0` in volume, issue

### ISSUE THREAD

**Issue by northword** [northword/zotero-format-metadata#20]
such as `01` should be `1`

**Comment by jiaojiaodubai** [comment]
Addendum: Similarly, do page numbers need to be filled with zeros and how many digits should be filled in.

**Comment by northword** [comment]
我简单搜索了一下，似乎 pages 也是去掉 `0` 就可以，而不需要补 0，您有需要补 0 的样式案例吗？

例如国标：
![image](https://github.com/northword/zotero-format-metadata/assets/44738481/ad811a45-b016-4dd7-90b1-abf068b35ea0)

**Comment by jiaojiaodubai** [comment]
@northword  我想到这个问题是因为我做翻译器的时候发现**报纸的版面**通常是前面补0的，比如“001版”、“01版”，这源自它的正式的印刷出版物上就是这样的写法，而不是数字化数据库的额外加工。不过并不了解是否有相关标准要求遵从这样的写法。

**Comment by northword** [comment]
这样可能会比较难判断补几个 0，因为不同的出版物一期/卷的页数不同，他们为了保持位数一致所以会补 0。而我们在 Z 里格式化这个主要是为了参考文献表，那在参考文献表范围内都去掉 0 是比较合理的（也许是吧）

**Comment by jiaojiaodubai** [comment]
如果确实需要补0的话（这可能是个伪需求），补多少应当交由用户设置的吧。

**Comment by jiaojiaodubai** [comment]
当前的实现可能有问题，如果期号是增刊、特刊，将无法有效去除多余的`0`。
如 [案例1](http://www.cqvip.com/qikan/Detail.aspx?gch=80553X&years=2018&num=S1)、[案例2](http://www.cqvip.com/qikan/Detail.aspx?gch=80553X&years=2015&num=B05)和[案例3](http://www.cqvip.com/qikan/Detail.aspx?gch=93364X&years=2005&num=Z1)

（我也中招了，很多转换器匹配`issue`的正则要修改）

**Comment by jiaojiaodubai** [comment]
当前的实现可能有问题，如果期号是增刊、特刊，将无法有效去除多余的`0`。
如 [案例1](http://www.cqvip.com/qikan/Detail.aspx?gch=80553X&years=2018&num=S1)、[案例2](http://www.cqvip.com/qikan/Detail.aspx?gch=80553X&years=2015&num=B05)和[案例3](http://www.cqvip.com/qikan/Detail.aspx?gch=93364X&years=2005&num=Z1)

（我也中招了，很多转换器匹配`issue`的正则要修改）

**Comment by northword** [comment]
你的意思是 `B05` -> `B5` 这种？

**Comment by jiaojiaodubai** [comment]
是的，我感觉这里的`0`也是多余的。
稍微检索了一下，Z代表合刊、S代表增刊，A、B代表上下册。
