### ISSUE TITLE
[Feature Request] 是否可以添加引用量了？

### ISSUE THREAD

**Issue by hsuanyong** [northword/zotero-format-metadata#204]
### Describe the feature

感谢你编写了如此优秀的插件。作为一个DOI功能集成的工具箱，要是可以添加引用量功能就更好了。crossref提供了开放的API接口可以查询引用量，API地址为：https://api.crossref.org/works/{doi}。例如DOI为：10.1016/j.scitotenv.2020.140827。通过替换{doi}可以查询信息，即https://api.crossref.org/works/10.1016/j.scitotenv.2020.140827，会返回一个页面，在页面中的“is-referenced-by-count”即引用量。希望可以在新版本中看到这个功能的更新。

**Comment by northword** [comment]
感谢您的建议。

Linter 目前主要针对与「创建参考文献表」有关的字段，这些字段基本上都是内建的字段或是 CSL 支持的字段。插件目前不考虑增加除此之外的字段支持。

此外，增加此功能可能会产生一系列的配套维护负担，如自定义列、是否自动更新引用量、自动更新引用量时的缓存机制等，我目前没有太多精力在插件上。

因此，Linter 短时间内不考虑增加「引用量」支持，建议您考虑通过 [Actions](https://github.com/windingwind/zotero-actions-tags) 完成此目标。
