### ISSUE TITLE
[Feature Request] 建议增加Lint时对物种学名保持首字母大写

### ISSUE THREAD

**Issue by caiisen** [northword/zotero-format-metadata#206]
### Describe the feature

目前的Lint无法识别物种学名，会自动把大写转换成小写。但是物种学名命名规范要求首字母大写，学名斜体。生物相关论文有大量标题含有物种学名，建议保持物种学名首字母大写。学名可以从斜体的单词去识别。

**Comment by northword** [comment]
插件默认不会修改斜体单词的大小写，例如标题 

```
测试 "条目" <i>AcPME</i>嗷嗷 《aa》 <11>
```

在 Lint 后，仍为

```
测试 "条目" <i>AcPME</i>嗷嗷 《aa》 <11>
```

`AcPME` 的大小写没有发生改变。

对于你所说的“学名可以从斜体的单词去识别。”，请首先确保你已经将学名设置为了斜体。如果插件修改了 `<i></i>` 内单词的大小写，请反馈一个示例。

否则，插件难以识别复杂的专有名词，也不可能内建所有学科的专有名词，你需要手动添加自定义术语。
