### ISSUE TITLE
[Bug] 手动添加 item，总是自动设置语言为en

### ISSUE THREAD

**Issue by Mctalos** [northword/zotero-format-metadata#211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: win10
- Zotero Version: 7
- Addon Version: 1.18.3

### Describe the bug

add new item ，任何类型，总是会自动设置语言为en。

<img width="310" alt="20240828_21-49-26" src="https://github.com/user-attachments/assets/b38f35e9-e658-4e0b-a67a-af1bdc02726b">

**Comment by northword** [comment]
Expected, the language falls back to `en` when Linter fails to detect the language of the `title`.

The next version will exclude new items.
