### ISSUE TITLE
[Feature Request] 删除英文标题末多余的句号 `.`

### ISSUE THREAD

**Issue by lllo-olll** [northword/zotero-format-metadata#213]
### Describe the feature

1、去掉英文作者名中间横线，或调整为空格
2、部分拉取的英文标题结尾有“.”，删除标题句末的“.”

**Comment by northword** [comment]
感谢反馈。

> 去掉英文作者名中间横线，或调整为空格

duplicate with #61 

> 部分拉取的英文标题结尾有“.”，删除标题句末的“.”

近期很忙，可能要到下月中上旬才有时间处理插件的反馈了。

**Comment by northword** [comment]
> 部分拉取的英文标题结尾有“.”，删除标题句末的“.”

我在实际处理中没有遇到过这种案例，你可以给几个例子吗？比如这种不规范的标题是从哪里来的（通过浏览器导入的还是附件抓取的？浏览器的话有没有实际的链接之类的，我好提前做好异常情况排除。

**Comment by lllo-olll** [comment]
1、示例：https://psycnet.apa.org/doiLanding?doi=10.1037%2Fpas0000648
![image](https://github.com/user-attachments/assets/4717e142-7ed3-4cb0-bbe8-b19d37dd47e8)
2、如果拉取此类数据则需要手动处理：
![image](https://github.com/user-attachments/assets/3b7b7083-bda9-47cd-806d-d2116a906560)
