### ISSUE TITLE
[Bug] 选择 [更新所有字段并lint]后会议文章变图书

### ISSUE THREAD

**Issue by holderhe** [northword/zotero-format-metadata#216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 11 22H2
- Zotero Version: 7.0.3
- Addon Version: 1.18.3

### Describe the bug

选择 [更新所有字段并lint]后会议文章变图书，即单篇会议文章变成整个会议集。不知道这一点是否是预期行为，如果是，该如何操作可能达到想要的结果，即只更新单篇会议的所有字段。
复现文章doi：10.1007/978-3-030-36708-4_23

**Comment by northword** [comment]
https://www.crossref.org/openurl/?pid=myemail@crossref.org&format=unixref&id=doi:10.1007/978-3-030-36708-4_23&noredirect=true

![Clip_2024-08-31_19-42-36](https://github.com/user-attachments/assets/081a35d3-1ff3-4fcb-a24c-4bf686fa5d1f)


![Clip_2024-08-31_19-40-51](https://github.com/user-attachments/assets/14db024a-70f9-4c86-993e-d5a7661d9002)

数据库有误，你可以向 CrossRef 反馈，或向 Zotero 官方反馈其转换器问题。

插件仅将数据库的元数据取回并保存，无力解决数据库数据准确性问题。

**Comment by northword** [comment]
插件更新元数据依次向 CrossRef (doi.org), ArXiv, SemanticScholar 请求数据，如果与以上数据库给出的信息不一致，请继续反馈，否则，插件也无法验证本地和远程的数据的准确性。

如果你的领域存在更完善的专业数据库，且该数据库提供公共 API 供其他程序调用，可以开新的 ISSUE 请求支持。

**Comment by northword** [comment]
反馈到哪里去呢？插件无法解决这类关于数据准确性的错误，因此反馈给我是无用的；CrossRef 仅提供了获取元数据的接口，不提供反馈错误的接口，因此反馈到 DOI 管理机构也不可行。

**Comment by northword** [comment]
如果你是从网页导入的（通过浏览器扩展 connector）是错误的，可以向 Zotero 官方反馈（因为官方维护着从网页抓去元数据的「转换器」）

如果你是根据 doi 导入的条目不对，可以看看 doi.org 记录的数据对不对，不对的话没办法了（也许可以考虑给 doi.org 发信，但这个地方的数据一般是出版商直接提供的）；如果doi.org记录的数据正确，但zotero 导入的不正确，可以向 zotero 官方反馈。

对于插件，如果报错了，直接向插件反馈。

没报错但数据不对，参考上面doi.org一段（因为插件调用的是 Zotero 的doi转换器的接口。

如果你发现 doi.org 上的不对，但其他数据库在你这个领域的准确度好得多，可以向插件反馈，我可以调整。

**Comment by northword** [comment]
CrossRef (doi.org), ArXiv, SemanticScholar 这个顺序已经是目前试出来的对于绝大部分文献，尤其是期刊论文，最稳定的了。

预印本和会议论文是最让人头疼的，这两类元数据相当混乱（相比于期刊论文）。

如果你发现 SemanticScholar 或其他数据来源对于会议论文的支持比 CrossRef 好得多，我可以加个这种选项。

**Comment by northword** [comment]
看了下，是由于包含 ISBN，导致优先根据 ISBN 查找了。

加了个逻辑判断当存在 DOI 时，优先使用 DOI。

已知问题：对于这篇文章，第一次更新全部字段，会从 会议论文 变为 图书章节（因为 DOI 数据库记录的是图书章节）；再次更新全部字段时，由于图书章节不包含 DOI，因此只能根据 ISBN 更新，将更新为 图书。

我个人建议没必要频繁“更新全部字段”，我只有当这个条目的数据看起来就不大正常时才会用这个。（当然因为我不太了解会议论文，我们领域以期刊论文为主，极少会议论文，可能会议论文有频繁更新的需求？）
