### ISSUE TITLE
[Feature Request] 为 Lint and Fix 增加一个快捷键

### ISSUE THREAD

**Issue by TomBener** [northword/zotero-format-metadata#219]
### Describe the feature

能否为 Lint and Fix 功能增加一个键盘快捷键，这样效率会高很多，每次右键点击感觉有点麻烦。谢谢！

**Comment by northword** [comment]
目前，新增条目可以自动 Lint and Fix，因此手动触发插件执行似乎是一个低频操作？

您的使用习惯需要频繁触发插件吗？

**Comment by TomBener** [comment]
我有很多以前保存的条目需要手动 Lint and Fix，不知道为什么，新增条目自动 Lint and Fix 经常不起作用

**Comment by northword** [comment]
Added shoutcuts `Ctrl + Alt + L` to run lint and fix.

Btw, Lint triggered in the menu supports batch processing, you can select multiple items to Lint at the same time.

**Comment by TomBener** [comment]
请问 macOS 上对应的快捷键是什么啊，谢谢！

**Comment by northword** [comment]
我没有 MAC 设备测试，你可以试一下 Control + Option + L？

**Comment by northword** [comment]
可否请你安装这个版本，然后打开 工具 -> 开发者 -> 控制台 ，然后依次按下 control、option、command ，并将控制台截图给我呢？

[linter-for-zotero-debug-keyboard.zip](https://github.com/user-attachments/files/17210646/linter-for-zotero-debug-keyboard.zip)


![Clip_2024-10-01_21-45-29](https://github.com/user-attachments/assets/1235f088-679b-4c0e-9968-2107b638ca55)

**Comment by TomBener** [comment]
我按您的提示做了，但按下 Control、Option、Command 后没有反应

![CleanShot 2024-10-01 at 21 58 29@2x](https://github.com/user-attachments/assets/9d9dff34-2e5a-44f3-aa34-4b9e4a5786f5)

**Comment by northword** [comment]
按下键盘时候需要聚焦到 Zotero 的主窗口，这个我漏说了

**Comment by TomBener** [comment]
明白了，这是新的截图

![CleanShot 2024-10-01 at 22 07 18@2x](https://github.com/user-attachments/assets/08047a78-ea7d-4dfe-80b5-9ec5bf943522)

**Comment by northword** [comment]
[linter-for-zotero-debug-keyboard-2.zip](https://github.com/user-attachments/files/17211000/linter-for-zotero-debug-keyboard-2.zip)

麻烦您再试一下这个可以正常使用 Control + Option + L 快捷键不？

**Comment by TomBener** [comment]
还是不行呢

**Comment by northword** [comment]
好奇怪，您方便远程控制嘛？如果方便的话，麻烦您加一下我的微信：northword

**Comment by northword** [comment]
[linter-for-zotero-debug-2fixed.zip](https://github.com/user-attachments/files/17373531/linter-for-zotero-debug-2fixed.zip)

经测试，在 macOS 上，option + L 会将 L 输出为 "¬" ，请尝试该版本是否修复快捷键问题？

快捷键应为 Command + Option + L。

**Comment by TomBener** [comment]
> [linter-for-zotero-debug-2fixed.zip](https://github.com/user-attachments/files/17373531/linter-for-zotero-debug-2fixed.zip)
> 
> 经测试，在 macOS 上，option + L 会将 L 输出为 "¬" ，请尝试该版本是否修复快捷键问题？
> 
> 快捷键应为 Command + Option + L。

可以了，非常感谢！

**Comment by fredericky123** [comment]
非常感谢！
请问如何为retrieve all and lint加个快捷键呢

**Comment by northword** [comment]
> 非常感谢！ 请问如何为retrieve all and lint加个快捷键呢 （需求场景，有时导入时是online版，写作时看到是online版本需要根据doi重新获取信息，更新为in print的卷 页码）

这似乎并不是一个高频操作，你可以通过 [Actions](https://github.com/windingwind/zotero-actions-tags?tab=readme-ov-file#create-your-own-actions) 插件实现，例如（未测试）：

```js
// Retrieve all fields and lint
// @usage Shortcut

if (item) {
  return
}

Zotero.Linter.hooks.onLintInBatch("getAllFieldViaDOIAndLint", items)
```

**Comment by fredericky123** [comment]
感谢！这样具体的操作就成了两个快捷键，先更新meta信息，再lint，如果能合二为一就好了

**Comment by fredericky123** [comment]
> > 非常感谢！ 请问如何为retrieve all and lint加个快捷键呢 （需求场景，有时导入时是online版，写作时看到是online版本需要根据doi重新获取信息，更新为in print的卷 页码）
> 
> 这似乎并不是一个高频操作，你可以通过 [Actions](https://github.com/windingwind/zotero-actions-tags?tab=readme-ov-file#create-your-own-actions) 插件实现，例如（未测试）：
> 
> // Retrieve all fields and lint
> // @usage Shortcut
> 
> if (item) {
>   return
> }
> 
> Zotero.Linter.hooks.onLintInBatch("getAllFieldViaDOIAndLint", items)

这个效果非常好，解决了英文online后正式出版时间等的更新问题，请问如果是知网的online后续想更新期刊号等，如何通过设置快捷键的方式实现呢？
目前设置的是option command U(pdate)，希望这个代码中自动判断是英文还是中文，英文根据doi，中文根据知网的最新网址信息
