### ISSUE TITLE
[Feature Request] 可以出一个会议名称到会议集名称的映射么

### ISSUE THREAD

**Issue by paridis-11** [northword/zotero-format-metadata#220]
### Describe the feature

就类似于期刊名称到期刊简称一样，比如会议名称是International Conference on Machine Learning，我希望将它在会议集名称自动转换为ICML

**Comment by northword** [comment]
但“会议集名称”似乎并不是“会议名称”的简写？

**Comment by zepinglee** [comment]
计算机领域的会议名称和简称可以参考 <https://www.ccf.org.cn/Academic_Evaluation/By_category/> 的 PDF 文档。

以 ICML 的这篇文章（<https://proceedings.mlr.press/v235/abad-rocamora24a.html>）为例，官方提供的 BibTeX 数据为：
```bib
```

**Comment by paridis-11** [comment]
是的是的，我想将会议的简称填入`proceedingsTitle`字段。想要这个功能，是为了方便在zotero中看到这篇文章是哪个会议的，不是为了方便引用。就像下面这个一样，我想直接看到ICML，而不是Proceedings of the 39th International Conference on Machine Learning.

![Uploading image.png…]()

**Comment by northword** [comment]
https://www.zotero.org/support/kb/item_types_and_fields#fields_for_presentations_and_performances

会议集名称不是会议名称的缩写，Linter 插件旨在维护正确的元数据填写在正确的字段上，这个需求似乎不太符合插件的目标。也许你需要类似于 #98 的东西？

**Comment by zepinglee** [comment]
> 想要这个功能，是为了方便在zotero中看到这篇文章是哪个会议的，不是为了方便引用。就像下面这个一样，我想直接看到ICML，而不是Proceedings of the 39th International Conference on Machine Learning.

我觉的这个需求有一定合理性，应该跟 #98 类似。

另外可以考虑这个功能：根据 `proceedingsTitle` 自动补齐 `conferenceName` 和 `shortConferenceName`，若后两者为空。

**Comment by paridis-11** [comment]
#98 这个功能怎么设置呢，我在设置里好像没有看到有关这个的相关描述。另外Zotero似乎也没有`shortConferenceName`这个字段

**Comment by paridis-11** [comment]
只要可以提供一个存放会议缩写，并且可以在Zotero主界面上调用显示的就好，最好还能使用这个缩写的字段重命名文件

**Comment by ljci** [comment]
同意，非常需要

**Comment by ljci** [comment]
journal abbreviations can only be used for journal article, can't be used for itemType that is conferencePaper. It is very annoying that paper from many of AI conference can not be extracted their meta data correctly but this is actually very demanding in zotero as many of people are doing AI research.

check https://github.com/Future-Scholars/paperlib for more details about what I am saying. The main function of this paperlib did what I just described, it can catch the meta data of the  paper from most of conference like NeruIPS, ECCV, ICML, ICLR and so on.

However, it is unnecessary to switch the software, so I really appreciate if author @northword can combine this function in zotero lint plugin, I would very appreciate your work. 

Also, I made a json file with most of AI conference for your reference, hope it helps
[transformed_conferences_2.json](https://github.com/user-attachments/files/17479677/transformed_conferences_2.json)

**Comment by northword** [comment]
将会议名称缩写存入 `proceedingsTitle` 不合理，可能会影响参考文献表输出，我想 可以在 extra 里写一个字段 `abbr`，然后新建一个“自定义列”，针对不同类型条目显示不同的内容：

- journalArticle：journalAbbreviation
- thesis: university
- conferencePaper: extra.abbr 或 shortConferenceName？
- patent: country
- ...: extra.abbr

这样应该可以解决这个问题和 #98 ，将于下个版本发布。

> 另外可以考虑这个功能：根据 proceedingsTitle 自动补齐 conferenceName 和 shortConferenceName，若后两者为空。

现在会议论文这块没有数据，也没有类似 abbrev.jabref.org 这种集中维护的库，如果有数据的话可以搞。

> check https://github.com/Future-Scholars/paperlib for more details about what I am saying. The main function of this paperlib did what I just described, it can catch the meta data of the paper from most of conference like NeruIPS, ECCV, ICML, ICLR and so on.

受限于我的个人精力，我目前没有计划为自动抓取元数据增加更多的功能，如果 Semantic Scholar 在你的领域支持较好的话可以考虑从 Semantic Scholar 更新元数据。

如果你有意增强此处功能，pr welcome。

**Comment by northword** [comment]
1.21.0 将 shortConferenceName 写入 extra，并提供一个 abbr 列来显示期刊缩写和 shortConferenceName 。

插件进内置了 @ljci 上传的部分会议名缩写，其余缩写可在设置项的“自定义缩写项”中定义，csv文件，第一列为会议名，第二列为缩写。

**Comment by sue-up** [comment]
我根据 @ljci 上传的会议名称json文件写了一个简易的会议名称信息更正javascript，可以修正会议名称混乱不统一以及easyscholar无法判断会议等级的问题（这个代码里直接将会议论文集的名称进行了统一，忽略了届数）。

将代码中的"json文件路径“替换为自己的路径即可。

以下是javaScript代码
```
zoteroPane = Zotero.getActiveZoteroPane();
items = zoteroPane.getSelectedItems();
//计数替换条目个数
var cnt = 0;


/**
 * checkAndAssign 函数用于处理字符串的替换操作。
 * @param {string} A - 用于比较的字符串
 * @param {object} B - 存储 json 文件数据的变量
 */
function checkAndAssign(A, B, item) {
    // 将 A 转换为小写，以便不区分大小写比较
    const lowerCaseA = A.toLowerCase();
    
    // 遍历 json 文件中的数据
    for (let key in B) {
        // 将第一列的字符串转换为小写
        const lowerCaseKey = key.toLowerCase();
        if (lowerCaseA.includes(lowerCaseKey)) {

            item.setField("proceedingsTitle", B[key][1]);
            item.setField("conferenceName", key);
            break;
        }
    }
    return 1;
}


// 读取 json 文件并将数据存储到变量 B 中
const fileContent = await Zotero.File.getContentsAsync("json文件路径", 'utf8');
const B = JSON.parse(fileContent);


// 处理 B 中第三列无字符串的情况
for (let key in B) {
    const value = B[key];
    // 检查该值是否不是数组且只有一个值
    if (!Array.isArray(value)) {
        v2 = "Proceedings of the " + key + " (" + value +")";
        B[key] = [value, v2];
    }
}


var ans = ""
for (var i = 0; i < items.length; i++) {
    var item = items[i]
    var isProceed = true
    var proceed = "";
    if (item.getField("proceedingsTitle") === "") {
        
        if (item.getField("conferenceName") === "") {
            
            isProceed = false
            proceed = item.getField("publicationTitle")
        }
        else{
            proceed = item.getField("conferenceName")
        }
    }
    else {
        
        proceed = item.getField("proceedingsTitle")
    }
    
    let bool = 0
    if (isProceed) {
        bool = checkAndAssign(proceed, B, item)
    }
    
    if (bool == 1) {
        ans = item.getField("title");
        cnt++;
    };
    
    await item.saveTx();
}

return cnt
```

以下是json文件，可以根据自己需要在文件中添加其它会议信息。
···
{
  "Association for the Advance of Artificial Intelligence": ["AAAI", "Proceedings of the AAAI Conference on Artificial Intelligence (AAAI)"],
  "Neural Information Processing Systems": ["NeurIPS", "Proceedings of the International Conference on Neural Information Processing Systems (NIPS)"],
  "Asian Conference on Computer Vision": ["ACCV", "Proceedings of the sian Conference on Computer Vision (ACCV)"],
  "ACM International Conference on Multimedia": ["ACM MM", "Proceedings of the ACM International Conference on Multimedia (ACM MM)"],
  "Computer Vision and Pattern Recognition": "CVPR",
  "European Conference on Computer Vision": ["ECCV", "Proceedings of the European Conference on Computer Vision (ECCV)"],
  "International Conference on Computer Vision": ["ICCV", "Proceedings of the IEEE/CVF International Conference on Computer Vision (ICCV)"],
  "International Joint Conference on Artificial Intelligence": ["IJCAI", "Proceedings of the International Joint Conference on Artificial Intelligence (IJCAI)"],
  "International Conference on Medical Image Computing and Computer Assisted Intervention Society": ["MICCAI", "Proceedings of the International Conference on Medical Image Computing and Computer Assisted Intervention Society (MICCAI)"],
  "International Conference on Learning Representations": "ICLR",
  "International Conference on Machine Learning": "ICML",
  "International Conference on Image Processing": "ICIP",
  "International Conference on Pattern Recognition": "ICPR",
  "Winter Conference on Applications of Computer Vision": "WACV",
  "Asian Conference on Machine Learning": "ACML",
  "European Conference on Machine Learning": "ECML",
  "International Conference on Learning Representations": "ICLR",
  "International Conference on Machine Learning": "ICML",
}
···

执行以上代码后，更新期刊标签，可以结合@northword 开发的shortConferenceName功能显示会议的简称，如下图：

![Image](https://github.com/user-attachments/assets/96250822-1e24-4b2c-842b-54153f161640)
