### ISSUE TITLE
[Bug] Lint错误的项目会清除所有标签

### ISSUE THREAD

**Issue by Les1ie** [northword/zotero-format-metadata#221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 11
- Zotero Version: 7.0.4-beta.2+974ac7861 (64-bit)
- Addon Version: 1.18.4

### Describe the bug

对于Lint错误的项目，会清除掉所有用户设置的标签，只保留插件设置的`linter/error`。

希望能将其设置为在原标签列表的基础上添加`linter/error`标签，而非直接覆盖。

**Comment by northword** [comment]
#222
