### ISSUE TITLE
[Bug] "IEEE Antennas and Wireless Propagation Letters" should be "IEEE Antennas Wireless Propag. Lett." instead of "IEEE Antennas Wirel. Propag. Lett.".

### ISSUE THREAD

**Issue by maxujiong** [northword/zotero-format-metadata#226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: 
- Zotero Version: 
- Addon Version:

### Describe the bug

"IEEE Antennas and Wireless Propagation Letters" should be "IEEE Antennas Wireless Propag. Lett." instead of "IEEE Antennas Wirel. Propag. Lett.".

### Anything else?

[IEEE-Abbreviations-for-Transactions-Journals-Letters.pdf](https://github.com/user-attachments/files/17057019/IEEE-Abbreviations-for-Transactions-Journals-Letters.pdf)

**Comment by northword** [comment]
![Clip_2024-10-01_16-26-03](https://github.com/user-attachments/assets/679970d8-f58b-4dc8-805c-2c9153308f0d)

Upstream data errors result, ref: https://github.com/JabRef/abbrv.jabref.org/issues/101 , and feedback to https://journal-abbreviations.library.ubc.ca is also required.
