### ISSUE TITLE
[Bug] Errors in the Treatment of Punctuation in the Publication Title

### ISSUE THREAD

**Issue by wenhspri** [northword/zotero-format-metadata#234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 11 Professional Edition 23H2
- Zotero Version: 7.0.5
- Addon Version: 1.19.1

### Describe the bug

Using Linter removes punctuation from the Journal Title, which is not practical and violates academic standards. For example, “Transportation Research Part C: Emerging Technologies” will automatically be changed to “Transportation Research Part C Emerging Technologies Technologies”.

**Comment by northword** [comment]
Waiting for upstream dataset fix.

![Clip_2024-10-04_20-26-45](https://github.com/user-attachments/assets/066ba228-b362-4d38-9bd0-552e68a81db1)
