### ISSUE TITLE
[Bug] subscript formatting may be incorrect

### ISSUE THREAD

**Issue by zousiyu1995** [northword/zotero-format-metadata#237]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 11 23H2
- Zotero Version: 7.0.7 (64-bit)
- Addon Version: 1.19.3

### Describe the bug

When I format this item, I found the subscript formatting is incorrect. There should not be an extra space between the text and the subscript. However, Linter ignore this.

```
Bahreini, Mohammad, Martin Désilets, Ergys Pahija, Ulrich Legrand, Jiaxun Guo和Arthur G. Fink. 《Investigation of CO 2 Reduction to Formate in an Industrial-Scale Electrochemical Cell through Transient Numerical Modeling》. Industrial & Engineering Chemistry Research, 2024年10月14日. https://doi.org/10.1021/acs.iecr.4c03239.
```

![image](https://github.com/user-attachments/assets/f4f3bb35-dc00-4ac5-81eb-d63cc85196b5)
![image](https://github.com/user-attachments/assets/55124325-a74e-44eb-b552-1d7d5587a04a)

**Comment by northword** [comment]
Linter does not currently handle subscripts and the spaces around them, merely providing buttons and shortcuts to help insert them, so you need to remove the spaces yourself.

**Comment by northword** [comment]
此外，我猜测你想反馈的问题是：选中2，通过Linter将其变为下标后，前面存在空格。

Linter 不会导致这个问题，我猜这个问题是由于你的标题本身，CO 和 2 之间就存在空格导致的。

**Comment by zousiyu1995** [comment]
> 此外，我猜测你想反馈的问题是：选中2，通过Linter将其变为下标后，前面存在空格。
> 
> Linter 不会导致这个问题，我猜这个问题是由于你的标题本身，CO 和 2 之间就存在空格导致的。

使用Linter“更新全部字段并Lint”时会存在该问题。

**Comment by northword** [comment]
> 使用Linter“更新全部字段并Lint”时会存在该问题。

经确认系 Zotero 转换器的错误，我将向 Zotero 官方反馈，在此之前你可以先手动去除空格。

**Comment by northword** [comment]
Track this issue here:

- https://forums.zotero.org/discussion/118815/extra-space-before-subscripts-in-title-when-importing-items-via-dois
- https://github.com/zotero/translators/pull/3374
- https://github.com/zotero/translators/issues/3375
