### ISSUE TITLE
作者你好，我想开发一个zotero注释笔记共享，方便他人阅读论文的插件。 我现在遇到一个问题是不了解zotero注释相关的api。不知能否帮助一下。

### ISSUE THREAD

**Issue by bhnan** [northword/zotero-format-metadata#243]
我简单的介绍一下我的想法吧。 我认为论文阅读时的标记注释，也是十分重要的知识，对于一个新手来说，可以大大降低入门门槛。
基于这个思路，我想开发一个可以共享大家论文注释的插件，大家简单的点击不懂的文本，如果别人有进行注释标记，就可以看到别人的注释，加速论文的理解。
我最近完成了一部分代码，但是由于对zotero开发不是十分了解，所以依旧有大量的问题bug，最主要的就是没有找到zotero获取注释信息相关的api。 希望作者能指条路，或者告诉我相关的信息，文档从哪里获得。 如果作者或者有人对这个插件有兴趣大家也可以一起开发，也可以给我提一点意见。

**Comment by northword** [comment]
https://github.com/windingwind/zotero-plugin-template/issues/203

1. API 请参阅 zotero-types 仓库，如 types 仓库尚未包含相关接口的声明，需要你前往 zotero/zotero 仓库或 zotero/reader 仓库查看源码来获取。
2. 目前没有关于 API 的完整文档，[web api](https://www.zotero.org/support/dev/web_api/v3/start) 似乎也没有相关的描述。
3. 我对 reader 部分不了解，但就咨询 api 而言，你应向 zotero developer mail list 询问：http://groups.google.com/group/zotero-dev
4. 你需要明确你的插件基本架构：数据存储在哪里？添加评论需要登陆？后端架设在哪里？他人回复的通知机制如何实现？如自己提供服务器，成本是否可以接受？这个类型有一些想论坛了，境内开办类似的通常需要企业资质，个人很难完成。
5. 正如 winding 所言，Zotero 提供的 groups 功能一定程度可以满足你的需求。
6. 我对这个想法的活跃度持保留意见：
  1. 我想你需要的是类似于小说阅读器、Notion侧边评论等的那种模式，但那种更带有娱乐色彩一些，和论文批注还是有些不同。当然，如果活跃度能很好，提出一个疑问，很快可以收到解答，听起来是极好的。
  2. 都要安装插件才能看到，前期推广时，人数过少，尤其分散到各个小行业中时，可能一个评论到他毕业都不会有回复，因此会卸载/禁用掉，以此恶性循环，除非前期就有手段大规模推广。否则大家仍会选择小木虫（通用）、科音论坛（DFT垂直领域）等等。
  3. 如果要做，还要区分正常的批注——因为有些是不方便公开的（如课题笔记），有些是纯自用的（如一定会有生词本）。
  4. 额外的，谁来审核内容？


总的来说，咨询 API 请前往 Zotero dev mail list，讨论插件需求也许可以在 Zotero Forums。

**Comment by bhnan** [comment]
感谢大佬提的建议。 我的思路是偏知识共享。
交互形式有点类似与微信读书中的下滑线标记。 点击后能够看到别人的注释——这样做的原因是基于一个思考，读文献时总会遇到不太懂的知识点，一般处理方式就是搜索引擎或者ai，但是前者来说获取时间长，流程复杂，而后者深度又不是很够，如果大家能把阅读记录分析出来，可以更方便后来者学习。 
这个我没打算做成评论交流的形式，只能进行阅读，评论的话内容可能就更随意了。
最开始的目标群体类似于课题组或者科研单位类似的。 但是理想化的想法是大家都能共享的话，才是一种好的科研状态。
不知大佬觉得我这个想法怎么样，有什么没有考虑到的吗？ 
------
我最开始的想法是开发一个知识共享的应用，比如说公众号中的论文解读那么多，能否把文献相关的内容聚合一下，方便论文阅读。但是由于复杂度以及引用权限的问题，就想到了zotero插件。
虽然这个时代大家都说知识付费，但是我觉得知识共享才是一个好的状态。

**Comment by northword** [comment]
> 这个我没打算做成评论交流的形式，只能进行阅读，评论的话内容可能就更随意了。

那为什么不用 Groups。

**Comment by bhnan** [comment]
> 那为什么不用 Groups。

我个人的看法是更简单吧，更符合直觉的交互，只需要点一下，也不需要进行额外的处理。 像groups类似的功能，其实有不少的实现，但是需要一些阅读习惯的养成，大多数都最后放弃了。 但是像是随手画一个注释，这个就很简单，可能会跟容易坚持下去吧。

**Comment by northword** [comment]
只能阅读的话注定只能小范围用，如课题组。只能阅读的话只需要做笔记加评论的人创建群组，阅读的人加入即可，我认为这与装插件的流程没什么区分。

我对这方面没有兴趣，无法给你更多帮助，你也许可以与你身边的人或在论坛讨论。
