### ISSUE TITLE
[Bug] 更新v1.21.0后，更新期刊abbr时报错，但之前没问题

### ISSUE THREAD

**Issue by ramonmi** [northword/zotero-format-metadata#244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Win11
- Zotero Version: Zotero 7.0.8
- Addon Version: 1.21.0

### Describe the bug

更新期刊abbr时报错，提示json文件格式有误，但之前版本没有遇到这个问题，json文件未改动
![image](https://github.com/user-attachments/assets/90b496e1-7252-4a36-a572-1f1a97ac9e41)
![image](https://github.com/user-attachments/assets/bac846b1-b7b0-4466-9334-0841249cb4e3)

**Comment by northword** [comment]
我这边测试正常呢，您方便发一下您的 JSON 文件吗？

**Comment by ramonmi** [comment]
v1.20.2正常，v1.21.0不行，json文件如下
[journal-abbr-data.json](https://github.com/user-attachments/files/17537091/journal-abbr-data.json)

**Comment by cjhonlyone** [comment]
v1.20.2正常，v1.21.0不行，json文件为空
![image](https://github.com/user-attachments/assets/5bcf26d4-1ee6-4462-b3a1-bea59c4d1439)

**Comment by easypickings** [comment]
Same error

**Comment by northword** [comment]
抱歉困扰，这是个很神奇的现象，开发模式和生产模式下，Zotero 接口返回的 JSON 文件的路径不一致，导致读取文件发生了错误，1.21.1 应修复了这个问题，请各位测试一下。
