### ISSUE TITLE
[Bug] 使用“根据标识符更新字段”后退出zotero更新未保存

### ISSUE THREAD

**Issue by zdl729** [northword/zotero-format-metadata#245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS:
- Zotero Version:7.0.9
- Addon Version:

### Describe the bug

1.更新字段后右侧信息栏未直接显示更新内容，需要点击其他条目后再点击才能显示。
2.更新后的字段（期刊的期卷页）退出zotero后重新打开后消失。
3.提一个小建议，能否在linter时删除下标和字母之间的空格，目前在linter时总会出现如，CO<sub>2</sub>→CO <sub>2</sub>的情况。

**Comment by northword** [comment]
3 -> 见 #237 ，这是 Zotero trasnslator 的问题，不是插件的问题。插件这边可以做个额外适配。

1，2 -> investigating。

这两天忙，我尽快处理。
