### ISSUE TITLE
[Bug] Linter 时显示 TypeError: data.forEach is not a function

### ISSUE THREAD

**Issue by luxaug** [northword/zotero-format-metadata#247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 11
- Zotero Version: 7.08
- Addon Version: 1.21.3

### Describe the bug

![Clip_2024-10-29_21-59-57](https://github.com/user-attachments/assets/e5dde61f-368d-4166-9883-a6e6dcab574b)

**Comment by northword** [comment]
是否设置了标题大小写自定义术语文件？如果设置了，该文件内容是否为空？若不为空，烦请提供该文件作为测试。

**Comment by northword** [comment]
前几个版本重构了加载数据的模块，增加了对后缀的校验，校验仅允许 `.csv`，没有考虑 `.CSV`，现已取消这个校验，请尝试 1.21.4。
