### ISSUE TITLE
[Bug] an inappropriate html tag exists in the title

### ISSUE THREAD

**Issue by zousiyu1995** [northword/zotero-format-metadata#250]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 11 23H2
- Zotero Version: 7.0.9 (64-bit)
- Addon Version: 1.21.6

### Describe the bug

When I lint and update all fields of refs. 1 and 2, there is an html tag around abbreviations such as `CFD`、`3D` and `CO2` in title field，
```
DOI: 10.1002/aic.18520
Title: A study of methanol‐to‐olefins packed bed reactor performance using particle‐resolved <span style="font-variant:small-caps;">CFD</span> and machine learning
```

```
DOI: 10.1002/aic.18336
Title: <span style="font-variant:small-caps;">3D</span> models guide the design of hollow fiber membrane contactors with complex internal structures for <span style="font-variant:small-caps;"> CO<sub>2</sub> </span> capture
```

However, for ref. 3, there is not a case.
```
DOI: 
Title: Simulating gas-solid phase isomerization of C8 aromatics affected by catalyst shapes in fixed bed reactors with particle-resolved CFD approach
```

**Comment by northword** [comment]
![Clip_2024-11-04_20-01-44](https://github.com/user-attachments/assets/c0396b27-5746-4901-8b07-bf4f09b9afff)

This is a CrossRef issue, the plugin doesn't handle this.
