### ISSUE TITLE
[Bug] 根据ISBN号查找中文图书信息报错

### ISSUE THREAD

**Issue by zousiyu1995** [northword/zotero-format-metadata#254]
### Describe the feature

中文图书，即便给出ISBN号，Linter也无法查找到图书信息。猜测是数据库没有中文图书的信息。不知是否可以增加能查找中文图书的数据库。

![image](https://github.com/user-attachments/assets/38035852-4365-4024-b101-736225322a7b)

**Comment by northword** [comment]
你给出的示例我测试正常，Zotero 版本及插件版本号？

![PixPin_2024-11-18_19-37-33](https://github.com/user-attachments/assets/1ab192c0-6ab7-467a-ae6b-c1faf04e47fa)

![PixPin_2024-11-18_19-37-56](https://github.com/user-attachments/assets/defecb76-f042-4bd9-bdae-d5531e5146cc)

**Comment by northword** [comment]
另外，Zotero 近期更新了 ISBN 识别规则，见 https://github.com/zotero/zotero/commit/d75d638337f014c00dfc5c3cbf5953e056162c28 。

若 Zotero v7.0.9 + 插件 v1.21.9 不能正常工作，请等待 Zotero v7.0.10 发布后再尝试，若 Zotero v7.0.10 + 最新版插件 无法正常工作，请继续在此 issue 中报告。

**Comment by northword** [comment]
Zotero 7.0.10 已发布，若问题仍然存在，请 reopen 此 issue。

**Comment by zousiyu1995** [comment]
已更新 7.0.11，仍然无法查找中文图书信息

**Comment by zousiyu1995** [comment]
@northword

**Comment by northword** [comment]
不是插件的问题，请向 Zotero 官方依如下格式汇报：

使用 “Add by Identifier...” 添加条目，输入 ISBN `978-7-115-29380-0` 后，没有查找到条目，然而此条目存在于 WorldCat 数据库中：`https://search.worldcat.org/zh-cn/title/952336882?oclcNum=952336882`。
