### ISSUE TITLE
[BUG] 错误的将预印本转为期刊文章

### ISSUE THREAD

**Issue by cesaryuan** [northword/zotero-format-metadata#37]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- OS: Windows 10 22H2
- Zotero Version: 6.0.26
- Addon Version: 0.4.2
```

### Describe the bug

对下面这篇文章执行【标准格式化流程】会错误的改变它的条目类型，从预印本变成了期刊文章

[[2306.03514] Recognize Anything: A Strong Image Tagging Model](https://arxiv.org/abs/2306.03514)

### Anything else?

https://github.com/northword/zotero-format-metadata/assets/35998162/04977c66-a018-445b-9bc0-338876942d9e

**Comment by northword** [comment]
感谢反馈，这是一个意料之外的错误，DOI translator 返回的信息显示他是一个期刊文章（虽然他确实还是一个预印本），可能是我对 DOI 转换器返回信息理解有错误导致的。

![image](https://github.com/northword/zotero-format-metadata/assets/44738481/8ae9bbd3-6ad5-46a9-8ee3-a9153b1b0a6f)

请更新 [4.0.3](https://github.com/northword/zotero-format-metadata/releases/tag/0.4.3) 版本试一下，这个版本中，我取消了更改条目类型这一行为。
