### ISSUE TITLE
[BUG] 页码检索错误

### ISSUE THREAD

**Issue by airsimonhan** [northword/zotero-format-metadata#38]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- OS: Windows 11 22H2
- Zotero Version: 6.0.26
- Addon Version: 0.4.4
```

### Describe the bug

在通过chrome插件直接导入论文的时候，发现zotero导入的page信息是正确的，但是过了一会儿之后，该插件会自动修正pages，修正之后的pages是错误的。
https://ieeexplore.ieee.org/abstract/document/9903546
修正前： 5800 - 5815
修正后：1-16

**Comment by northword** [comment]
请在首选项中关闭 在标准格式化流程中通过doi更新期卷页等字段  这一选项。
更新后的数据是来自于doi，新版本插件已经默认禁用了这个功能。
