### ISSUE TITLE
Calls for journal abbreviation errors | 期刊缩写错误征集

### ISSUE THREAD

**Issue by northword** [northword/zotero-format-metadata#5]
In English: 

The journal abbreviation data built into the plugin comes from JabRef, and we would like to thank all the maintainers and contributors of the JabRef journal abbreviation repository.
The dataset is very large, and some errors are inevitable.
Please feedback any errors you find here, and we will send them upstream and change them as soon as possible, or you can give feedback directly to https://github.com/JabRef/abbrv.jabref.org.

---

In Chinese: 

插件内置的期刊缩写数据来自 JabRef，谨在此向 JabRef 期刊缩写仓库的所有维护人员和贡献者表示感谢。
该数据集非常大，里面的不可避免地会出现一些错误，还请谅解。
请将发现的错误缩写反馈于此，我们反馈给上游并尽快更改，你也可以直接向上游反馈：https://github.com/JabRef/abbrv.jabref.org。

**Comment by fredericky123** [comment]
很多本领域的顶刊竟然都没缩写，是这个缩写库不全吗
比如Administrative Science Quarterly, Journal of Management都应该有缩写，我更新的时候却无法更新

**Comment by northword** [comment]
> 很多本领域的顶刊竟然都没缩写，是这个缩写库不全吗
> 比如Administrative Science Quarterly, Journal of Management都应该有缩写，我更新的时候却无法更新

1.0.0 版本开始，只内置了来自哥伦比亚大学图书馆提供的约 1 万条缩写，包括 Chemistry, Chemical Engineering, Materials Engineering, Electrical and Computer Engineering, Earth and Ocean Sciences, and Physical Geography at the University of British Columbia 等领域。

JabRef 的库中存在较多错误，被临时移除了，我正在整理这个数据库，完毕后会重新加进来。

下一版本我先把 JabRef 的数据加回来，再慢慢整理。

**Comment by northword** [comment]
https://github.com/northword/zotero-format-metadata/releases/tag/1.6.8

**Comment by fredericky123** [comment]
> https://github.com/northword/zotero-format-metadata/releases/tag/1.6.8

感谢感谢，果然可以更新了

**Comment by LiuJ00** [comment]
1.6.9和1.6.10版本下，Journal of the American Chemical Society缩写成了JACS，是错误的，1.6.8版本的缩写正确

**Comment by northword** [comment]
> 1.6.9和1.6.10版本下，Journal of the American Chemical Society缩写成了JACS，是错误的，1.6.8版本的缩写正确

1.6.11 修复

**Comment by pengxy0** [comment]
Angewandte Chemie, International Edition，最新版这个期刊的全称和简称中间都多一个逗号，希望修复。
