### ISSUE TITLE
请问哪里能下载到自定义缩写json文件？

### ISSUE THREAD

**Issue by jlu511** [northword/zotero-format-metadata#51]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- OS:win10
- Zotero Version: beta 33
- Addon Version: 1.44
请问哪里能下载到自定义缩写json文件zotero-format-metadata-custom-abbr-data？
```

### Describe the bug

请问哪里能下载到自定义缩写json文件zotero-format-metadata-custom-abbr-data？

### Anything else?

请问哪里能下载到自定义缩写json文件zotero-format-metadata-custom-abbr-data？

**Comment by jlu511** [comment]
目前，内部自带的缩写，对于Angewandte Chemie International Edition，缩写为Angew. Chem. - Int. Ed.，而实际为Angew. Chem. Int. Ed.。对于Journal of Energy Chemistry，没有数据。对于Acta Physica Sinica，缩写为Acta Phys. Sinica，而实际为Acta Phys. Sin-Ch. Ed.。
请问是否能更新或通过自定义缩写库更正。能否下载到相关缩写数据库。非常感谢您的付出。

**Comment by northword** [comment]
1.5.0 更新了内置的期刊缩写数据的来源，Angewandte Chemie International Edition 和 Journal of Energy Chemistry 现均以可以正确匹配到。

经查询，Acta Physica Sinica 的正确 ISO 缩写应为 Acta Phys. Sin. ，没有中文版后缀 [^1]。

[^1]: 在 Web of Science 查询：https://jcr.clarivate.com/jcr-jp/journal-profile?journal=ACTA%20PHYS%20SIN-CH%20ED&year=2022 ，附图
![图片](https://github.com/northword/zotero-format-metadata/assets/44738481/c4122da8-cedd-47a7-a015-8aaabfb2ec54)
