### ISSUE TITLE
[BUG] 如果指定一个空的期刊缩写“自定义数据文件”，在进行更新时会报错

### ISSUE THREAD

**Issue by Geo123abc** [northword/zotero-format-metadata#52]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- OS: Windows 11 22H2
- Zotero Version: 7.0.0 beta33
- Addon Version: v1.4.5
```

### Describe the bug

如果指定一个空的期刊缩写“自定义数据文件”，在进行更新时会报错。

### Anything else?

“自定义数据文件”如果支持csv格式，那么用户编辑起来可能会方便一些，但是软件性能不知道是否有影响。

### 功能增加：

“期刊”词首大写（这个也放在“标准格式化流程”）

### 功能改进：

“根据条目标题自动更新语言字段”能否支持自定义，如果识别为中文则填写为“zh”，如果识别为英文，则填写为“en”，用户的既有习惯可能和“ISO 639 Code”不一致，更激进一些，允许自定义一个ISO 639 Code和用户自定义缩写的对照表（类似期刊缩写“自定义数据文件”，但是意义可能不大）

**Comment by northword** [comment]
> 如果指定一个空的期刊缩写“自定义数据文件”，在进行更新时会报错。

我未能复现， “空的期刊缩写'自定义数据文件'” 是指没有选择 自定义缩写文件，还是自定义缩写文件是空文件？
如果是后者，这是预期的：文件必须是语法正确的，JSON 文件为空的正确语法是 `{}`，为不是空文件。如果是这种的话我可以再做一个异常捕获。

> “自定义数据文件”如果支持csv格式，那么用户编辑起来可能会方便一些，但是软件性能不知道是否有影响。

影响倒是不太大，csv 有个问题就是分隔符到底是逗号还是分号，目前 excel 编辑 csv 是按地区的，有的地区用逗号，有的地区用分号，这意味着插件和用户都要同时对逗号和分号转义。
而且再一个暂时没做 csv 的原因纯粹就是我太懒 xs


> “期刊”词首大写（这个也放在“标准格式化流程”）

有计划，这段时间比较忙还没来得及写，我准备周末再做。

不过这个看起来不复杂，但是要收集不少专有词汇，如 ACS Catalysis 中的 ACS 是始终保持大写的，这个需要加一组豁免词。我也只计划在全大写的期刊名中应用，不是全大写的保持原有不变，以防把原来正确的改成错的。你有什么更好的想法嘛？

对于每一个字段是否存在，是否应该存在，存在的大小写、格式等，已有数据的有效性等，都有计划做，以更符合 Linter 这个名字。

> “根据条目标题自动更新语言字段”能否支持自定义，如果识别为中文则填写为“zh”，如果识别为英文，则填写为“en”，用户的既有习惯可能和“ISO 639 Code”不一致，更激进一些，允许自定义一个ISO 639 Code和用户自定义缩写的对照表（类似期刊缩写“自定义数据文件”，但是意义可能不大）

ISO 639 - ISO 3166 是 Zotero 官方建议。至少 ISO 639 代码是必须填进去的，这样 CSL 才能正常工作。

目前只有 `cmn` -> `zh-CN`, `eng` -> `en-US` 这两个自动匹配了 ISO 3166 代码，其余的都是 ISO 639 直接填上，eng 的映射应该会在之后的版本移除，只有 cmn 的映射，参考 https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/issues/160 。

针对 ISO 3166 的对照可以做，之前也考虑过，但是优先级会比较低。

**Comment by Geo123abc** [comment]
我json语法搞错了

csv格式也是使用 [zoushucai/zotero-journalabbr: zotero期刊缩写](  https://github.com/zoushucai/zotero-journalabbr  )    过程中看到的，这个插件设置中允许用户选择分隔符（见下图），然后我觉得这种格式是用户友好的，便于编辑

![](https://s3.bmp.ovh/imgs/2023/08/15/7f614c2b52cb5b37.png)


> “期刊”词首大写（这个也放在“标准格式化流程”）
大小写误伤的问题我之前欠考虑，但是我有一个想法，如果扩充期刊缩写“自定义数据文件”为三列，在目前的两列基础上增加一列 “ 标准的“期刊”词首大写”，然后使用这个数据库做匹配；如果匹配不到，就强制词首大写。

对于第三列的维护，一般来讲用户接触的期刊是有限的，可以考虑让用户自己编辑，工作量也还可以接受，或者搞一个在线的Excel表格，让社区的人进行编辑，你定期更新到插件里面

**Comment by northword** [comment]
csv 可能会比较靠后实现，我个人其实也不太倾向用户使用自定义缩写，https://github.com/northword/zotero-format-metadata/issues/48#issuecomment-1674234890 ，我看看，之后做一下。

期刊词首大写豁免词这个可以提前收拾出来一些，有缺漏了用户反馈就行，我想应该不会很多。
“搞一个在线的Excel表格，让社区的人进行编辑，你定期更新到插件里面” 也是可以的。
