### ISSUE TITLE
存在错误，请在控制台查看错误信息

### ISSUE THREAD

**Issue by xiongfly** [northword/zotero-format-metadata#67]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: windows 11
- Zotero Version:  Zotero 7 beta.39
- Addon Version: 1.6.2

### Describe the bug

![image](https://github.com/northword/zotero-format-metadata/assets/130461183/cfccbd3b-c000-4f13-82b5-e176fa66369a)
最近老是用不了，出现“存在错误，请在控制台查看错误信息”。

**Comment by northword** [comment]
![图片](https://github.com/northword/zotero-format-metadata/assets/44738481/9309f5a3-2cbd-4620-ab52-32cde9613c1b)

请提供控制台报错信息，如果可能，同时提供发生错误的条目信息。

**Comment by xiongfly** [comment]
[Linter for Zotero] An error occurred and the detailed error log is shown below: 
 
Array [ "No items returned from any translator", {…} ]
​
0: "No items returned from any translator"
​
1: Object { _ObjectType: "Item", _objectTypePlural: "items", _ObjectTypePlural: "Items", … }
​​
_ObjectType: "Item"
​​
_ObjectTypePlural: "Items"
​​
_ObjectsClass: Object { _ZDO_object: "item", _primaryDataSQLFrom: "FROM items O LEFT JOIN itemAttachments IA USING (itemID) LEFT JOIN items IAP ON (IA.parentItemID=IAP.itemID) LEFT JOIN itemNotes INo ON (O.itemID=INo.itemID) LEFT JOIN items INoP ON (INo.parentItemID=INoP.itemID) LEFT JOIN itemAnnotations IAn ON (O.itemID=IAn.itemID) LEFT JOIN items IAnP ON (IAn.parentItemID=IAnP.itemID) LEFT JOIN deletedItems DI ON (O.itemID=DI.itemID) LEFT JOIN publicationsItems PI ON (O.itemID=PI.itemID) LEFT JOIN charsets CS ON (IA.charsetID=CS.charsetID)LEFT JOIN groupItems GI ON (O.itemID=GI.itemID) LEFT JOIN feedItems FI ON (FI.itemID=O.itemID)", _relationsTable: "itemRelations", … }
​​
_annotationAuthorName: null
​​
_annotationColor: null
​​
_annotationComment: null
​​
_annotationImage: null
​​
_annotationIsExternal: null
​​
_annotationPageLabel: null
​​
_annotationPosition: null
​​
_annotationSortIndex: null
​​
_annotationText: null
​​
_annotationType: null
​​
_attachmentCharset: ""
​​
_attachmentContentType: ""
​​
_attachmentLastProcessedModificationTime: null
​​
_attachmentLinkMode: 1
​​
_attachmentPath: ""
​​
_attachmentSyncState: null
​​
_attachmentSyncedHash: null
​​
_attachmentSyncedModificationTime: null
​​
_attachments: Object { rows: (2) […], chronologicalWithTrashed: null, chronologicalWithoutTrashed: null, … }
​​
_bestAttachmentState: Object { type: "pdf", exists: true }
​​
_changed: Object {  }
​​
_changedData: Object {  }
​​
_collections: Array [ 74 ]
​​
_createdByUserID: null
​​
_creatorIDs: Array(5) [ 349, 4691, 4692, … ]
​​
_creators: Array(5) [ {…}, {…}, {…}, … ]
​​
_dataTypesToReload: Set []
​​
_dateAdded: "2023-09-04 03:07:50"
​​
_dateModified: "2023-09-04 03:07:55"
​​
_deleted: false
​​
_disabled: false
​​
_displayTitle: "Monascin and ankaflavin act as novel hypolipidemic and high-density lipoprotein cholesterol-raising agents in red mold dioscorea"
​​
_feedItemGUID: ""
​​
_feedItemReadTime: ""
​​
_feedItemTranslatedTime: ""
​​
_fileExists: null
​​
_firstCreator: "Lee 等"
​​
_hasNote: null
​​
_id: 10285
​​
_identified: true
​​
_inCache: true
​​
_inPublications: false
​​
_itemData: Object { 1: "Monascin and ankaflavin act as novel hypolipidemic and high-density lipoprotein cholesterol-raising agents in red mold dioscorea", 2: "Monascus-fermented red mold dioscorea (RMD) has been proven to possess greater hypolipidemic effect than red mold rice (RMR) even though they include equal levels of cholesterol-lowering agent monacolin K. However, higher concentrations of yellow pigments (monascin and ankaflavin) were found in RMD than in RMR. In this study, purified monascin and ankaflavin were administered to hyperlipidemic hamsters for 8 weeks, respectively, to test whether these two compounds were novel hypolipidemic ingredients. In the statistical results, monascin and ankaflavin showed significant effect on lowering cholesterol, triglyceride, and low-density lipoprotein cholesterol levels in serum, as well as aorta lipid plaque (p < 0.05). Importantly, monascin and ankaflavin, unlike monacolin K, were able to perform up-regulation rather than down-regulation on high-density lipoprotein cholesterol (HDL-C) levels in serum. This finding not only explained why RMD showed greater hypolipidemic and HDL-C-raising effect than RMR but also proved that monascin and ankaflavin would act as novel and potent hypolipidemic ingredients.", 6: "2010-08-25 2010-08-25", … }
​​
_itemTypeID: 21
​​
_key: "PZUPP9NV"
​​
_lastModifiedByUserID: null
​​
_libraryID: 1
​​
_loaded: Object { primaryData: true, creators: true, itemData: true, … }
​​
_noteAccessTime: null
​​
_noteText: null
​​
_noteTitle: null
​​
_notes: null
​​
_objectTypePlural: "items"
​​
_parentID: false
​​
_parentKey: false
​​
_previousData: Object {  }
​​
_relations: Array []
​​
_skipDataTypeLoad: Object { note: true }
​​
_sortCreator: "Lee Chun-Lin Kung Yi-Hsin Wu Cheng-Lun"
​​
_synced: true
​​
_tags: Array(12) [ {…}, {…}, {…}, … ]
​​
_version: 58296
​​
<prototype>: Object { constructor: Item(), _objectType: "item", ContainerObjectsClass: Getter, … }
​
length: 2
​
<prototype>: Array []
谢谢大佬，我找到原因了，应该是我挂的梯子所选的节点访问不了更新题录的网站😂

**Comment by northword** [comment]
bd4ddc1b7bf94834ccacefc84ea19889c1ffbd23

1.6.3 起报错信息也将展示在进度提示框。
