### ISSUE TITLE
[BUG] 富文本工具框已弹出但无法前台显示

### ISSUE THREAD

**Issue by mulei000** [northword/zotero-format-metadata#69]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 11 
- Zotero Version: 7 beta 38
- Addon Version: 1.6.2

### Describe the bug

改上标下标的窗口有显示打不开

**Comment by mulei000** [comment]
任务栏有预览小窗口，但是打不开

**Comment by northword** [comment]
无法复现，请提供完整的复现步骤、插件版本、Zotero 版本。

**Comment by northword** [comment]
经群内交流，疑似系统问题，暂时关闭。

**Comment by mulei000** [comment]
交流后以解决，但不确定是否可以通用，出现该情况可以尝试右键选择任务栏预览的富文本工具箱窗口，选择最大化，尝试解决
