### ISSUE TITLE
[Feature Request] 请问可否增加“双引号”和“单引号”，“单双书名号”互相转换的功能

### ISSUE THREAD

**Issue by yzy1228682367** [northword/zotero-format-metadata#72]
### Describe the feature

大佬请问可否增加“双引号”和“单引号”，“单双书名号”互相转换的功能呢？因为有的引注格式标题要求用“双引号”或者“双书名号”，所以文章标题本身的“双引号”或者“双书名号”就只能改为“单引号”或者“单书名号”。

### Additional context
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/issues/202 csl似乎无法实现这一功能。

**Comment by northword** [comment]
双书名号是`《》`嘛？单书名号是`<>`？

**Comment by yzy1228682367** [comment]
> 双书名号是`《》`嘛？单书名号是`<>`？

对的！

**Comment by northword** [comment]
@yzy1228682367 如我在 https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/issues/204#issuecomment-1712401476 所测试的，CSL 似乎可以正常处理引号和书名号，这个功能仍是需要吗？

另外，刚刚发现，单书名号是 `〈〉`而非 `<>` 。

**Comment by northword** [comment]
经过与 zeping lee 的讨论可知，CSL 可以正常处理引号，所以插件仅需要替换中文书名号。

考虑到这个功能可能不是大部分同学都需要，且我不确定这种替换会不会对其他方面造成影响，所以没有将其加入自动流程，其位置如下图：

![图片](https://github.com/northword/zotero-format-metadata/assets/44738481/9293d8c5-9e01-4434-b616-56e95f0e7c10)

**Comment by yzy1228682367** [comment]
感谢大佬！抱歉昨天一直在办活动今天才看到(/∇＼*)
