### ISSUE TITLE
[Feature Request] 这个能提醒重复？能关闭点击标题出现的框吗？

### ISSUE THREAD

**Issue by earthmoon** [northword/zotero-format-metadata#73]
### Describe the feature

您好，

我想问两个问题：

1. 当导入重复的文献，会有提示吗？我使用时发现没有提示；
2. 点击文献题目，出现一个提示框，我只想用快捷键，这个框可以关闭吗？

谢谢！

**Comment by northword** [comment]
1.  插件版本与zotero版本？该功能未在 0.4.4 实现。
2. 首选项中关闭

**Comment by earthmoon** [comment]
> 1. 插件版本与zotero版本？该功能未在 0.4.4 实现。
> 2. 首选项中关闭

谢谢！0.4.4. Zotero 7.0稳定版还没出，我不敢用。所以用Zotero6. 等后面升级吧。谢谢你！
