### ISSUE TITLE
[Bug] “案例”和“法律”格式运行“将标题中《》转为<>”后标题会被改变

### ISSUE THREAD

**Issue by yzy1228682367** [northword/zotero-format-metadata#75]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: macos 
- Zotero Version:  zotero 7 beta 39
- Addon Version:  1.6.4

### Describe the bug

“案例”和“法律”格式运行“将标题中《》转为<>”后标题会被改变。
![CleanShot 2023-09-11 at 08 28 08@2x](https://github.com/northword/zotero-format-metadata/assets/50101175/c92f0998-7ea2-45d3-8968-1e2c54a6a9be)
![CleanShot 2023-09-11 at 08 30 41@2x](https://github.com/northword/zotero-format-metadata/assets/50101175/fb1d70af-2cee-4826-bbf6-e45382266385)

**Comment by northword** [comment]
这是全都替换成空的了吗？

**Comment by northword** [comment]
你可以通过 tools->developer->Run Javascript 运行如下
```js
const items =  Zotero.getActiveZoteroPane().getSelectedItems();
for (item of items) {
    console.log(item,item.getField("nameOfAct"),item._previousData.title)
    item.setField("nameOfAct", item._previousData.title);
    item.saveTx()
}

```
来尝试恢复标题。

**Comment by northword** [comment]
如同 #77 描述的，这个问题我要晚点才能搞了，请你先不要用这个功能处理所有的法律条目，造成的麻烦还请谅解。

**Comment by yzy1228682367** [comment]
没有没有，是我要感谢大佬出了转化书名号的功能。

**Comment by yzy1228682367** [comment]
不过请问zotero的数据怎么备份呢？好像zotero本身没有这个功能？

**Comment by northword** [comment]
> 不过请问zotero的数据怎么备份呢？好像zotero本身没有这个功能？

是的，我是对库里条目进行大批量更新时候会手动备份一份数据库，在 首选项/高级/数据存储位置 里可以看到一个 `.sqllite` 的数据文件，复制一份就可以。

（也建议你尽量不要对库里大批量的更改）（不要信任任何插件，大部分插件开发者都是兼职开发，尤其是 Zotero 的插件开发者，大部分都是学生，水平和考虑的测试的范围并不大，所以很可能出现问题）

**Comment by yzy1228682367** [comment]
感谢您，学到了！

**Comment by yzy1228682367** [comment]
感谢大佬，我目前用的预印本、网页、期刊文章、报纸文章、学位论文、图书、司法案例、法律、标准都没有出现这个问题。

**Comment by northword** [comment]
> 感谢大佬，我目前用的预印本、网页、期刊文章、报纸文章、学位论文、图书、司法案例、法律、标准都没有出现这个问题。

收到，感谢测试 :)
