### ISSUE TITLE
[Bug] 运行“将标题中《》转为<>”没有反应

### ISSUE THREAD

**Issue by yzy1228682367** [northword/zotero-format-metadata#76]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: macos
- Zotero Version: zotero 7 beta 39
- Addon Version: 1.6.4

### Describe the bug

运行“将标题中《》转为<>”没有反应。
https://github.com/northword/zotero-format-metadata/assets/50101175/b56e5046-0802-48cc-902a-36ef1ac71270

**Comment by northword** [comment]
我把两个菜单写反了，新版本应该修复了这个问题。

**Comment by yzy1228682367** [comment]
好的 感谢大佬~
