### ISSUE TITLE
[Bug] 大佬，请问可不可以增加一个“点击标题不弹窗”的设置？

### ISSUE THREAD

**Issue by yzy1228682367** [northword/zotero-format-metadata#78]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: macos
- Zotero Version: beta39 
- Addon Version: 1.6.6

### Describe the bug

这个弹窗偶尔卡住加载不出来，而且不会自己消除，另外感觉似乎用快捷键就可以解决？
![CleanShot 2023-09-13 at 20 16 14@2x](https://github.com/northword/zotero-format-metadata/assets/50101175/d80431b9-39a4-45cf-987c-e239d94ce63d)

**Comment by northword** [comment]
![图片](https://github.com/northword/zotero-format-metadata/assets/44738481/a3317645-1712-4781-ab80-df6209fa488e)

**Comment by northword** [comment]
这个弹不出来有比较稳定的复现方式吗？

点击标题过快（来回切换编辑状态那种）可能是会导致弹窗出问题

**Comment by yzy1228682367** [comment]
> ![图片](https://user-images.githubusercontent.com/44738481/267648311-a3317645-1712-4781-ab80-df6209fa488e.png)

哦吼多谢大佬！

> 这个弹不出来有比较稳定的复现方式吗？ 点击标题过快（来回切换编辑状态那种）可能是会导致弹窗出问题

目前发现的是，如果是第一次点击就比较容易出现，如果本来就是弹出完整的话就似乎不会再出现。

**Comment by northword** [comment]
> 目前发现的是，如果是第一次点击就比较容易出现，如果本来就是弹出完整的话就似乎不会再出现。

我在 Windows 上无法重复这个现象，可能是 Mac 上的一些玄学 bug ，不过好在你也不用这个233

另外可以麻烦你看下 https://github.com/northword/zotero-format-metadata/issues/23 这个问题嘛？
就是这个弹窗，当他弹出来以后，是否是置顶的（始终在Zotero主窗口之前，哪怕鼠标已经点了 Zotero 主窗口，这个富文本工具框仍然是在最前的），在 MAC & Zotero 6 上是有一些问题，不知道在 7 上正常了不

**Comment by yzy1228682367** [comment]
我的不会始终是置顶的，点击主窗口后会被主窗口挡住。

**Comment by northword** [comment]
> 我的不会始终是置顶的，点击主窗口后会被主窗口挡住。

收到，那看来是仍然有问题。

感谢！

**Comment by northword** [comment]
收到
