### ISSUE TITLE
[Feature Request] 请问是否可以自定义期刊缩写（批量）

### ISSUE THREAD

**Issue by Coriolis-a** [northword/zotero-format-metadata#82]
### Describe the feature

为了节省空间想要标注期刊缩写，但是可能因为方向太小众很多识别不正确或者还是太长。现在发现可以手动修改期刊缩写，但是对于有些期刊识别后的结果一致，手动修改条目太多，如果可以批量修改就好了。（或者可以编辑库吗？）谢谢！（第一次用github不知道是不是这样提问题）

**Comment by northword** [comment]
没太看明白你的需求，如果只是自定义期刊缩写，请参考：

https://github.com/northword/zotero-format-metadata/issues/48#issuecomment-1676282436

![image](https://github.com/northword/zotero-format-metadata/assets/44738481/25edb303-f168-4bb2-8a45-c556ade7d0e8)

**Comment by Coriolis-a** [comment]
我的菜单里没有这项啊。。。
<img width="426" alt="image" src="https://github.com/northword/zotero-format-metadata/assets/147395926/355f400f-b171-49f8-a42d-1d2503ed08ab">

**Comment by northword** [comment]
你是 Zotero 6 还是 Zotero 7？插件版本是哪个？

0.4.4 版本没有这个功能，插件已经不再维护 Zotero 6 版本（0.4.4）了。

**Comment by Coriolis-a** [comment]
哭了。官网都没有7于是下载了6. 好不容易配置好了担心换成7前功尽弃

**Comment by northword** [comment]
你可以编辑 XPI 文件，这是一个压缩包，用 解压缩软件打开它（可以不解压直接编辑，大部分压缩软件都支持编辑后自动保存），找到 `chrome/content/scripts/index.js 或 formatmetadata.js` ，在里面搜索对应的期刊名称，把缩写部分改成你需要的，然后保存。

0.4.4 版本内置了 9w 多条缩写，你仍然有大量缩写不正确嘛？

**Comment by northword** [comment]
此外，你可以尝试 journalabbr 插件，这个插件适配 Z6 版本的好像支持自定义缩写。

**Comment by Coriolis-a** [comment]
嗯啊 我看了你给我的那条 我和那个楼主想法差不多  想要几个字母缩写自己知道是哪个期刊就可以了  自动缩写好多不怎么合适 甚至有没缩写的（开始怀疑插件有没有在我的上面生效 是安装自动生效吗
）

**Comment by northword** [comment]
插件不影响安装插件前就已经存在的条目，你需要手动更新才行。

期刊缩写字段仅建议存储标准 ISO 4 缩写，而不是只是几个首字母的缩写形式。
