### ISSUE TITLE
“重复条目检查”开关

### ISSUE THREAD

**Issue by occasional15** [northword/zotero-format-metadata#84]
### Describe the feature

是否可以增加“重复条目检查”开关？每次使用其他插件（GreenFrog）更新条目信息时都会弹窗“发现重复条目”，但实际上更新完成后并无重复条目，还必须手动关闭弹窗。所以想要手动关闭此功能。

**Comment by northword** [comment]
这个开关可以加，我下周空了改一下。

关于你描述green frog更新条目信息会导致本插件弹窗的问题，这应是green frog插件的问题，他在更新条目信息时，是新保存了一个条目到文献库，用新条目的信息替换原条目后，删除新条目。但translator提供了参数以在不改变文献库的情况下返回重新抓取的元数据。

如果针对英文文献，本插件也提供了通过doi更新条目信息的功能，可供缓解此问题。

**Comment by occasional15** [comment]
> “通过doi更新字段（所有）”

我发现“通过doi更新字段（所有）”这一操作并未执行“标准格式化流程”，导致需要分2步进行。“通过doi更新字段（所有）”功能能否包含“标准格式化流程”功能呢？

**Comment by northword** [comment]
> > “通过doi更新字段（所有）”
> 
> 我发现“通过doi更新字段（所有）”这一操作并未执行“标准格式化流程”，导致需要分2步进行。“通过doi更新字段（所有）”功能能否包含“标准格式化流程”功能呢？

确实是这么设计的，目的是为了保持 从crossref/doi.org 等数据库获取到的元数据的原始性，从而方便判断 是插件工作错误 还是数据库元数据信息的问题。

**Comment by occasional15** [comment]
> 确实是这么设计的，目的是为了保持 从crossref/doi.org 等数据库获取到的元数据的原始性，从而方便判断 是插件工作错误 还是数据库元数据信息的问题。

好的谢谢，或许可以考虑一个合并后的单独功能选项。

**Comment by northword** [comment]
> > 确实是这么设计的，目的是为了保持 从crossref/doi.org 等数据库获取到的元数据的原始性，从而方便判断 是插件工作错误 还是数据库元数据信息的问题。
> 
> 好的谢谢，或许可以考虑一个合并后的单独功能选项。

也可以，回头我加个选项
