### ISSUE TITLE
[Feature Request] Sentence-case 连字符或冒号后单词首字母大写

### ISSUE THREAD

**Issue by panmengguan** [northword/zotero-format-metadata#85]
### Describe the feature

目前 Sentence-case 连字符或冒号后单词的首字母会变成小写，是否应该是大写呢？

**Comment by northword** [comment]
这是一个颇有争议的问题，有人认为需要大写，也有人认为不需要。z7版本内置的逻辑是 better bibtex 插件作者写的，他和 zotero 的开发者 dan 都认可了小写。我回头再查一查有没有规范，实在不行加个选项也行。

**Comment by panmengguan** [comment]
我是 EE 专业的，IEEE 规范是连字符或冒号后单词的首字母大写。

**Comment by fredericky123** [comment]
https://onlinelibrary.wiley.com/doi/10.1002/smj.3553
我们领域都是小写，目前这个连字符前后的单词全被改成了大写
![image](https://github.com/northword/zotero-format-metadata/assets/13982749/b35d0e51-109a-40ce-afac-b06edfcf570a)

**Comment by northword** [comment]
> [https://onlinelibrary.wiley.com/doi/10.1002/smj.3553[ ](https://sci-hub.se/10.1002/smj.3553)](https://onlinelibrary.wiley.com/doi/10.1002/smj.3553) 我们领域都是小写，目前这个连字符前后的单词全被改成了大写 ![image](https://user-images.githubusercontent.com/13982749/280203289-b35d0e51-109a-40ce-afac-b06edfcf570a.png)

未能复现，你安装的是哪个版本的插件？

**Comment by fredericky123** [comment]
> > [https://onlinelibrary.wiley.com/doi/10.1002/smj.3553[ ](https://sci-hub.se/10.1002/smj.3553)]([https://onlinelibrary.wiley.com/doi/10.1002/smj.3553[  ](https://sci-hub.se/10.1002/smj.3553)](https://onlinelibrary.wiley.com/doi/10.1002/smj.3553)) 我们领域都是小写，目前这个连字符前后的单词全被改成了大写 ![image](https://user-images.githubusercontent.com/13982749/280203289-b35d0e51-109a-40ce-afac-b06edfcf570a.png)
> 
> 未能复现，你安装的是哪个版本的插件？

批量standard format时导致的，不过我现在也不能复现了，下次遇到再说

**Comment by zepinglee** [comment]
这里的冒号通常是分隔主标题和副标题，按照美国英语的主流习惯是冒号后要大写。

APA <https://apastyle.apa.org/style-grammar-guidelines/capitalization/sentence-case>

> In sentence case, lowercase most words in a title or heading. Capitalize only the following words:
> ...
> the first word after a colon, em dash, or end punctuation in a heading

Chicago:

<img width="609" alt="Screenshot 2024-01-01 at 21 33 22" src="https://github.com/northword/zotero-format-metadata/assets/12290822/9676f386-9963-489f-a24a-6cb2885726ee">

IEEE <http://journals.ieeeauthorcenter.ieee.org/wp-content/uploads/sites/7/IEEE_Reference_Guide.pdf> p. 7

<img width="747" alt="Screenshot 2024-01-01 at 21 36 32" src="https://github.com/northword/zotero-format-metadata/assets/12290822/aa97e568-a8ef-4035-af44-83fa254cdfa8">

**Comment by northword** [comment]
我有点拿不准这个，因为部分样式，即便是 Zotero 里存储的是 冒号后为小写的 Sentence style，CSL 仍可以显示为正确的  冒号后为大写的 Sentence style，例如 APA：

![image](https://github.com/northword/zotero-format-metadata/assets/44738481/4868e5ce-4ebd-46e2-9351-c21ada7d9e8f)

那么会不会出现部分样式本就要求 冒号后是小写的 Sentence style ，然而 Zotero 里存了大写，导致输出错误的？

**Comment by zepinglee** [comment]
> 我有点拿不准这个，因为部分样式，即便是 Zotero 里存储的是 冒号后为小写的 Sentence style，CSL 仍可以显示为正确的 冒号后为大写的 Sentence style，例如 APA：
> 
> 那么会不会出现部分样式本就要求 冒号后是小写的 Sentence style ，然而 Zotero 里存了大写，导致输出错误的？

奇怪，我能在 Zotero 中复现你的结果，但是用 citeproc-test-runner 在 citeproc-js 中不会产生大写的“Design”。

```diff
      + expected - actual
<div class="csl-bib-body">
-  <div class="csl-entry">Yuan, C., Wu, H. B., Xie, Y., &#38; Lou, X. W. (David). (2014). Mixed transition-metal oxides: design, synthesis, and energy-related applications. <i>Angewandte Chemie International Edition</i>, <i>53</i>(6), 1488–1504. https://doi.org/10.1002/anie.201303971</div>
+  <div class="csl-entry">Yuan, C., Wu, H. B., Xie, Y., &#38; Lou, X. W. (David). (2014). Mixed transition-metal oxides: Design, synthesis, and energy-related applications. <i>Angewandte Chemie International Edition</i>, <i>53</i>(6), 1488–1504. https://doi.org/10.1002/anie.201303971</div>
</div>
```

我怀疑是 Zotero 的这个 style editor 对字段信息作了某些处理。

**Comment by northword** [comment]
根据 Zotero 官方的意见，存储于 Zotero 标题字段中的句子式大写不需要在冒号或连字符（副标题）后给大写，Zotero 可以自动完成副标题的大写，对于有多个冒号或连字符的，应把主标题填写在“短标题”字段[^Zotero文档][^pr评论]。

[^Zotero文档]: https://www.zotero.org/support/kb/sentence_casing#sentence_case_and_subtitles

[^pr评论]: https://github.com/zotero/utilities/pull/31#issuecomment-1985167342

---

@zepinglee 我们在 CSL 的测试上可能需要考虑到类似的问题，我不确定 Zotero 是否还会处理其他字段（目前还没有发现）。

---

如果没有问题，此 issue 将在跟进 https://github.com/zotero/utilities/pull/31，https://github.com/zotero/zotero/issues/3787 后关闭。

**Comment by zepinglee** [comment]
嗯，那我没问题了。
