### ISSUE TITLE
[Feature Request] 将标题改为 sentence-case 加入标准格式化流程

### ISSUE THREAD

**Issue by panmengguan** [northword/zotero-format-metadata#86]
### Describe the feature

是否有可能将把将标题改为句首大写加入标准格式化流程呢？

**Comment by northword** [comment]
这个功能没有经过很多其他专业的文献标题的测试，可能会导致一些错误，我计划把它加到流程里，不过短时间内是默认不启用这个功能的。

**Comment by northword** [comment]
1.6.7 中添加，默认启用。
