### ISSUE TITLE
[Bug] PDF拖入后，条目元数据的语言无法自动更新

### ISSUE THREAD

**Issue by LiuJ00** [northword/zotero-format-metadata#89]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: MacOS 13.6.1
- Zotero Version: 7.0.0-beta.51
- Addon Version: 1.6.11

### Describe the bug

外部PDF拖入zotero后，自动生成的条目元数据的语言无法自动更新，只有手动 标准化格式流程 后语言才能改为en-US。在zotero6和0.4.4版本使用时，正常使用。

![CleanShot 2023-11-17 at 21 15 30@2x](https://github.com/northword/zotero-format-metadata/assets/136417116/f4bdf035-629f-443d-9e1a-36bd132ef268)

**Comment by northword** [comment]
无法复现，请确认“新增条目时更新”已开启，且无其他插件干扰。
