### ISSUE TITLE
[Bug] 会议论文更新 publicationTitle 会影响 proceedingsTitle

### ISSUE THREAD

**Issue by Leonezz** [northword/zotero-format-metadata#94]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 11
- Zotero Version: 7
- Addon Version: 1.6.11

### Describe the bug

对无 DOI 的文献条目执行标准化流程会导致一些已有的字段如会议名等被清空。

### Anything else?

这样的行为似乎逻辑不通，如果插件需要 DOI 才能获取条目元数据并进行标准化，那么无 DOI 的文献就不应该被改动。

**Comment by northword** [comment]
标准格式化流程暂时还没涉及清空已有字段的行为。
标准流行默认没有启用通过doi更新信息。
通过doi更新信息时，如果没有doi，会直接中断操作。
其他所有函数中均未涉及会议名称这一字段。

请确认是否是其他插件导致。
如果确认是本插件行为，请提供详细的条目信息、插件设置信息、复现流程。

**Comment by Leonezz** [comment]
找了一个示例文献，bib 如下：
```bib
@inproceedings{liao-veeramachaneni-2009-simple,
    title = "A Simple Semi-supervised Algorithm For Named Entity Recognition",
    author = "Liao, Wenhui  and
      Veeramachaneni, Sriharsha",
    editor = "Wang, Qin Iris  and
      Duh, Kevin  and
      Lin, Dekang",
    booktitle = "Proceedings of the {NAACL} {HLT} 2009 Workshop on Semi-supervised Learning for Natural Language Processing",
    month = jun,
    year = "2009",
    address = "Boulder, Colorado",
    publisher = "Association for Computational Linguistics",
    url = "https://aclanthology.org/W09-2208",
    pages = "58--65",
}
```

运行插件的录屏：

https://github.com/northword/zotero-format-metadata/assets/33564074/53491e51-202b-4f04-97d0-51ba04cccf3c

**Comment by northword** [comment]
简单排查了一下，初步判断是与 #77 类似的问题，我将于近期修复。

**Comment by northword** [comment]
你好，该问题已尝试在此版本修复：https://github.com/northword/zotero-format-metadata/releases/tag/v1.6.15

**Comment by Leonezz** [comment]
试了下确实好了，感谢！
