### ISSUE TITLE
Missing Book Title When saving the Book Chapter

### ISSUE THREAD

**Issue by asifnawaz01** [northword/zotero-format-metadata#95]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- MacOS: 14.1.2 (23B92) 
- Zotero Version: 7.0.0-beta.51+7c5600913
- Addon Version: 1.6.11

### Describe the bug

Thank you so much for this awesome plugin.

When I save the book chapter in Zotero, it fails to save the book title from the webpage, which I then have to manually update. It has been happening consistently. Any help is appreciated. Attached is a screenshot of my Linter plugin settings.
<img width="1427" alt="Screenshot 2023-12-02 at 15 54 38" src="https://github.com/northword/zotero-format-metadata/assets/127496344/c2f5f357-fe8e-4d73-b086-3ed658358098">

**Comment by northword** [comment]
If the information is incomplete when saving an item from a web page, feedback should be given to the Zotero forums, this may be a bug of the translator.
