### ISSUE TITLE
[Bug] 通过 doi 更新字段时日期错误

### ISSUE THREAD

**Issue by zzlb0224** [northword/zotero-format-metadata#96]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: win11
- Zotero Version: 7.0.0-beta.52+2f8e536f2 (64-bit)
- Addon Version: 1.6.11

### Describe the bug

10.1108/ITP-12-2020-0870
Article publication date: 24 September 2021 
Issue publication date: 19 July 2023

使用 **通过DOI更新所有字段** 的时候年份是不是填错了？我觉得应该是2021年，更新后是2023年

**Comment by northword** [comment]
![image](https://github.com/northword/zotero-format-metadata/assets/44738481/f46c37dc-0968-4444-93f9-26a13feaf06f)
给出示例的日期无误。

1. 请区分在线（online publication）时间和出版（期卷页 publication）时间。
2. 通过 doi 更新数据时，数据来自 crossref 或 doi.org，这两个数据库的信息均有期刊提供。
3. 我们和数据库都无法保障数据的绝对准确，在更新后仍需人工确认。

**Comment by zzlb0224** [comment]
谢谢解答，是我理解错了
