### ISSUE TITLE
关于缩写的本地JSON文件及相关的问题

### ISSUE THREAD

**Issue by Caccar** [northword/zotero-format-metadata#97]
### Describe the feature

感谢作者开发的插架，功能强大且好用。

下面想建议一下，因为插架支持加载本地JSON格式的期刊名及对应的期刊缩写名称。而且每位研究生在不同的领域可能对自己领域内的部分期刊有显示缩写的需求。想问一下作者能不能提供一下如果想自己创建本地JSON格式的缩写文件，这个文件所遵从的基本格式是什么，或者您在里面写两条示例，然后由我们自己填写相关缩写。
[
![CleanShot 2023-12-09 at 09 44 11@2x](https://github.com/northword/zotero-format-metadata/assets/128353132/4d343d86-4a03-4bd6-bade-4e757bee19d9)
](url)
例如：Management Science这本期刊，插件提供的缩写是Manage Sci，而我们领域一般都称呼为“MS”即可。

如果能提供JSON由大家自主进行相关缩写的名称应该会更好。

再次感谢作者！！！

**Comment by northword** [comment]
请查阅：https://github.com/northword/zotero-format-metadata/issues/48
